"""Tests for MCP server discovery + HTTP catalog + gating.

These guard the post-skills MCP feature: we never install MCP servers
ourselves, we *scan* the user's machine for configs that other tools
(Claude Desktop, Cursor, Codex) already set up, normalize them to
MultiServerMCPClient's schema, and surface them to the agent + UI.

The autouse fixture in `conftest.py` disables disk scanning by
default. Tests in this file re-enable it via
`monkeypatch.setenv("SHEJANE_LOCAL_MCP_DISCOVERY", "on")` and point
`HOME` at a tmp_path so the scan finds only fixture files instead of
the developer's real Claude Desktop config.
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
import tempfile
from contextlib import asynccontextmanager
from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from mcp.client.stdio import StdioServerParameters

from local_host.config import reset_settings_for_tests
from local_host.server import create_app
from local_host.tools.mcp import (
    MAX_MCP_DESCRIPTION_CHARS,
    MAX_MCP_SCHEMA_DEPTH,
    SOURCE_CLAUDE_DESKTOP,
    SOURCE_CODEX,
    SOURCE_CURSOR,
    SOURCE_ENV,
    SOURCE_SHEJANE,
    _normalize_entry,
    discover_servers,
    mcp_sensitive_values,
    validate_mcp_tools,
)
from local_host.tools.mcp_stdio import MCPStdioFrameTooLargeError, bounded_stdio_client


@pytest.mark.asyncio
async def test_stdio_frame_limit_rejects_before_json_parsing() -> None:
    server = StdioServerParameters(
        command=sys.executable,
        args=["-c", "print('x' * 128, flush=True)"],
    )
    async with bounded_stdio_client(server, max_frame_bytes=32) as (read, _write):
        result = await read.receive()
    assert isinstance(result, MCPStdioFrameTooLargeError)


def _isolate_home(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    """Re-enable disk scan + redirect HOME so discovery only sees
    what THIS test wrote. Returns the fake home for convenience."""
    monkeypatch.setenv("SHEJANE_LOCAL_MCP_DISCOVERY", "on")
    monkeypatch.setenv("HOME", str(tmp_path))
    # macOS-only fallback for Path.home() — older Python honors $HOME
    # first, but we set it anyway for belt-and-suspenders.
    monkeypatch.delenv("USERPROFILE", raising=False)
    return tmp_path


# ---------------------------------------------------------------------------
# _normalize_entry — schema sanity
# ---------------------------------------------------------------------------


def test_normalize_stdio_default_transport() -> None:
    norm = _normalize_entry("fs", {"command": "npx", "args": ["-y", "fs-mcp"]})
    assert norm is not None
    assert norm["transport"] == "stdio"
    assert norm["command"] == "npx"
    assert norm["args"] == ["-y", "fs-mcp"]


def test_normalize_http_url_infers_streamable_http() -> None:
    norm = _normalize_entry("remote", {"url": "https://api.example.com/mcp"})
    assert norm is not None
    assert norm["transport"] == "streamable_http"
    assert norm["url"] == "https://api.example.com/mcp"


def test_normalize_websocket_url_infers_ws_transport() -> None:
    norm = _normalize_entry("rt", {"url": "wss://realtime.example.com"})
    assert norm is not None
    assert norm["transport"] == "websocket"


def test_normalize_explicit_transport_wins() -> None:
    norm = _normalize_entry("x", {"transport": "sse", "url": "https://api.example.com/sse"})
    assert norm is not None
    assert norm["transport"] == "sse"


@pytest.mark.parametrize("alias", ["http", "streamable-http"])
def test_normalize_http_transport_aliases(alias: str) -> None:
    norm = _normalize_entry(
        "remote",
        {"transport": alias, "url": "https://api.example.com/mcp"},
    )
    assert norm is not None
    assert norm["transport"] == "streamable_http"


def test_normalize_missing_command_and_url_returns_none() -> None:
    # Claude Desktop sometimes has entries like {"disabled": true} with
    # nothing else — we should drop instead of crashing later.
    assert _normalize_entry("x", {"args": ["foo"]}) is None


def test_normalize_disabled_flag_returns_none() -> None:
    # Claude Desktop opt-out convention: user marked it disabled.
    assert _normalize_entry("x", {"command": "npx", "disabled": True}) is None


def test_normalize_coerces_args_to_strings() -> None:
    # Some users (or autogenerated configs) pass ints; subprocess
    # would crash on those without coercion.
    norm = _normalize_entry("x", {"command": "node", "args": ["server.js", 8080]})
    assert norm is not None
    assert norm["args"] == ["server.js", "8080"]


def test_normalize_strips_nested_env_values() -> None:
    # Env values must be strings — drop dicts/lists silently.
    norm = _normalize_entry(
        "x",
        {
            "command": "node",
            "env": {"KEY": "value", "BAD": {"nested": 1}, "NULL_VAL": None},
        },
    )
    assert norm is not None
    assert norm["env"] == {"KEY": "value"}


def test_normalize_non_dict_returns_none() -> None:
    assert _normalize_entry("x", "not a dict") is None
    assert _normalize_entry("x", None) is None


def test_mcp_metadata_rejects_configured_secret(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from langchain_core.tools import tool

    secret = "secret-value-12345"
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps(
            {
                "remote": {
                    "url": "https://example.com/mcp",
                    "headers": {"Authorization": f"Bearer {secret}"},
                }
            }
        ),
    )

    @tool("mcp.remote.leak")
    def leaking_tool(value: str = secret) -> str:
        """A tool whose server-controlled schema echoes a credential."""
        return value

    sensitive = mcp_sensitive_values(tmp_path)
    assert any(secret in value for value in sensitive)
    assert validate_mcp_tools([leaking_tool], sensitive_values=sensitive) == []

    @tool(secret)
    def leaking_name(value: str) -> str:
        """A tool whose name echoes a credential."""
        return value

    assert (
        validate_mcp_tools(
            [leaking_name],
            sensitive_values=sensitive,
        )
        == []
    )


def test_mcp_metadata_enforces_size_depth_and_name_boundaries() -> None:
    from langchain_core.tools import tool

    @tool("mcp.safe.lookup")
    def safe_tool(value: str) -> str:
        """Look up one value."""
        return value

    @tool("mcp.too.large", description="x" * (MAX_MCP_DESCRIPTION_CHARS + 1))
    def large_tool(value: str) -> str:
        return value

    deep_schema: dict[str, object] = {"type": "object"}
    cursor = deep_schema
    for _ in range(MAX_MCP_SCHEMA_DEPTH + 1):
        child: dict[str, object] = {}
        cursor["properties"] = child
        cursor = child

    accepted = validate_mcp_tools(
        [safe_tool, large_tool, safe_tool],
        reserved_names={"mcp.reserved"},
    )
    assert [item.name for item in accepted] == ["mcp.safe.lookup"]
    assert accepted[0].args_schema["type"] == "object"
    assert (
        validate_mcp_tools(
            [safe_tool],
            reserved_names={"mcp.safe.lookup"},
        )
        == []
    )
    safe_tool.args_schema = deep_schema
    assert validate_mcp_tools([safe_tool]) == []


# ---------------------------------------------------------------------------
# discover_servers — disk scan gate
# ---------------------------------------------------------------------------


def test_discover_skips_disk_when_flag_off(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    # conftest sets DISCOVERY=off by default. Without an env var, we
    # get nothing — even though we'd be scanning the real home dir.
    monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
    out = discover_servers(tmp_path)
    assert out == []


def test_discover_env_override_works_even_when_disk_off(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # Env var is the explicit-config path and must work regardless of
    # the disk-scan flag — useful for tests + one-off debugging.
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"e": {"command": "node", "args": ["e.js"]}}),
    )
    out = discover_servers(tmp_path)
    assert len(out) == 1
    assert out[0].name == "e"
    assert out[0].source == SOURCE_ENV
    assert out[0].config["transport"] == "stdio"


def test_discover_env_accepts_mcpservers_wrapper(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"mcpServers": {"e": {"command": "node"}}}),
    )
    out = discover_servers(tmp_path)
    assert [s.name for s in out] == ["e"]


def test_discover_malformed_env_logged_and_skipped(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("SHEJANE_LOCAL_MCP_SERVERS", "{not valid json")
    out = discover_servers(tmp_path)
    assert out == []


# ---------------------------------------------------------------------------
# discover_servers — multi-source disk scan
# ---------------------------------------------------------------------------


def test_discover_reads_shejane_user_config(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    home = _isolate_home(monkeypatch, tmp_path)
    monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
    shejane_dir = home / ".shejane"
    shejane_dir.mkdir(parents=True, exist_ok=True)
    (shejane_dir / "mcp-servers.json").write_text(
        json.dumps({"mcpServers": {"local-fs": {"command": "npx", "args": ["fs"]}}}),
        encoding="utf-8",
    )
    out = discover_servers(tmp_path)
    names = [s.name for s in out]
    assert "local-fs" in names
    fs = next(s for s in out if s.name == "local-fs")
    assert fs.source == SOURCE_SHEJANE
    assert "mcp-servers.json" in fs.source_path


def test_discover_reads_claude_desktop_macos(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import sys

    if sys.platform != "darwin":
        pytest.skip("Claude Desktop macOS path only")
    home = _isolate_home(monkeypatch, tmp_path)
    monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
    claude_dir = home / "Library" / "Application Support" / "Claude"
    claude_dir.mkdir(parents=True, exist_ok=True)
    (claude_dir / "claude_desktop_config.json").write_text(
        json.dumps(
            {
                "mcpServers": {
                    "claude-fs": {"command": "npx", "args": ["fs-server"]},
                    "claude-disabled": {"command": "x", "disabled": True},
                }
            }
        ),
        encoding="utf-8",
    )
    out = discover_servers(tmp_path)
    names = [s.name for s in out]
    assert "claude-fs" in names
    # Disabled servers must NOT show up — user opted out.
    assert "claude-disabled" not in names
    cf = next(s for s in out if s.name == "claude-fs")
    assert cf.source == SOURCE_CLAUDE_DESKTOP


def test_discover_reads_cursor_config(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    home = _isolate_home(monkeypatch, tmp_path)
    monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
    cursor_dir = home / ".cursor"
    cursor_dir.mkdir(parents=True, exist_ok=True)
    (cursor_dir / "mcp.json").write_text(
        json.dumps({"mcpServers": {"cur-fs": {"command": "npx", "args": ["fs"]}}}),
        encoding="utf-8",
    )
    out = discover_servers(tmp_path)
    sources = {s.source for s in out}
    assert SOURCE_CURSOR in sources


def test_discover_reads_codex_toml(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    home = _isolate_home(monkeypatch, tmp_path)
    monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
    codex_dir = home / ".codex"
    codex_dir.mkdir(parents=True, exist_ok=True)
    (codex_dir / "config.toml").write_text(
        """
[mcp_servers.codex-fs]
command = "node"
args = ["server.js"]
""".strip(),
        encoding="utf-8",
    )
    out = discover_servers(tmp_path)
    sources = {s.source for s in out}
    assert SOURCE_CODEX in sources
    cf = next(s for s in out if s.name == "codex-fs")
    assert cf.config["command"] == "node"


def test_discover_dedupes_by_name_first_source_wins(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """When the same server name appears in shejane (higher priority)
    and Claude Desktop (lower), the shejane version wins. This lets
    users locally override a Claude config without editing it."""
    import sys

    if sys.platform != "darwin":
        pytest.skip("multi-source dedupe test pinned to macOS Claude path")
    home = _isolate_home(monkeypatch, tmp_path)
    monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
    # shejane has the canonical version
    shejane_dir = home / ".shejane"
    shejane_dir.mkdir(parents=True, exist_ok=True)
    (shejane_dir / "mcp-servers.json").write_text(
        json.dumps({"mcpServers": {"fs": {"command": "shejane-fs"}}}),
        encoding="utf-8",
    )
    # Claude has a different one with the same name
    claude_dir = home / "Library" / "Application Support" / "Claude"
    claude_dir.mkdir(parents=True, exist_ok=True)
    (claude_dir / "claude_desktop_config.json").write_text(
        json.dumps({"mcpServers": {"fs": {"command": "claude-fs"}}}),
        encoding="utf-8",
    )
    out = discover_servers(tmp_path)
    # Exactly one entry named "fs", and it's the shejane one.
    fs_entries = [s for s in out if s.name == "fs"]
    assert len(fs_entries) == 1
    assert fs_entries[0].source == SOURCE_SHEJANE
    assert fs_entries[0].config["command"] == "shejane-fs"


def test_discover_malformed_disk_file_skipped(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    home = _isolate_home(monkeypatch, tmp_path)
    monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
    shejane_dir = home / ".shejane"
    shejane_dir.mkdir(parents=True, exist_ok=True)
    (shejane_dir / "mcp-servers.json").write_text("{ not json", encoding="utf-8")
    # Should not raise — just no entries from this source.
    out = discover_servers(tmp_path)
    assert all(s.source != SOURCE_SHEJANE for s in out)


# ---------------------------------------------------------------------------
# HTTP — GET /local/v1/mcp-servers
# ---------------------------------------------------------------------------


@pytest.fixture
def client(monkeypatch: pytest.MonkeyPatch) -> TestClient:
    """Spin up the daemon with an isolated tmp data dir + tok auth.

    Doesn't enable disk scan — tests that want disk scan flip the
    SHEJANE_LOCAL_MCP_DISCOVERY env per test body.
    """
    tmp = Path(tempfile.mkdtemp(prefix="jdl-mcp-"))
    os.environ["SHEJANE_LOCAL_HOST_TOKEN"] = "tok"
    settings = reset_settings_for_tests(
        SHEJANE_LOCAL_HOST_ADDR="127.0.0.1",
        SHEJANE_LOCAL_HOST_PORT=17371,
        SHEJANE_LOCAL_HOST_TOKEN="tok",
        data_dir=tmp,
    )
    app = create_app(settings)
    with TestClient(app) as c:
        yield c


def test_http_mcp_servers_empty_default(client: TestClient) -> None:
    # autouse fixture disables disk scan; no env var; expect 0 servers
    # but sources_scanned still populated so UI can hint user where to
    # drop configs.
    r = client.get("/local/v1/mcp-servers", headers={"Authorization": "Bearer tok"})
    assert r.status_code == 200
    body = r.json()
    assert body["servers"] == []
    # Always-present source labels regardless of scan toggle
    assert "env" in body["sources_scanned"]
    assert "shejane" in body["sources_scanned"]


def test_http_mcp_servers_lists_env_entries(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    # Setting the env var should produce one normalized server row.
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps(
            {
                "mcpServers": {
                    "github": {
                        "command": "npx",
                        "args": ["-y", "@modelcontextprotocol/server-github"],
                        "env": {"GITHUB_TOKEN": "ghp_secret_value"},
                    }
                }
            }
        ),
    )
    r = client.get("/local/v1/mcp-servers", headers={"Authorization": "Bearer tok"})
    assert r.status_code == 200
    body = r.json()
    assert len(body["servers"]) == 1
    s = body["servers"][0]
    assert s["name"] == "github"
    assert s["transport"] == "stdio"
    assert s["source"] == "env"
    assert s["command"] == "npx"
    assert s["args"] == ["-y", "@modelcontextprotocol/server-github"]
    # SECURITY: env *keys* surface, env *values* MUST NOT.
    assert s["env_keys"] == ["GITHUB_TOKEN"]
    assert "ghp_secret_value" not in json.dumps(body)


def test_http_mcp_server_crud_writes_only_shejane_config(
    client: TestClient, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    home = _isolate_home(monkeypatch, tmp_path)
    payload = {
        "name": "context7",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@upstash/context7-mcp"],
        "env": {"CONTEXT7_API_KEY": "secret-value"},
    }

    created = client.post(
        "/local/v1/mcp-servers",
        headers={"Authorization": "Bearer tok"},
        json=payload,
    )
    assert created.status_code == 200, created.text
    assert created.json()["server"]["name"] == "context7"

    config_path = home / ".shejane" / "mcp-servers.json"
    raw = json.loads(config_path.read_text(encoding="utf-8"))
    assert raw["mcpServers"]["context7"]["command"] == "npx"
    assert raw["mcpServers"]["context7"]["env"]["CONTEXT7_API_KEY"] == "secret-value"

    listed = client.get("/local/v1/mcp-servers", headers={"Authorization": "Bearer tok"})
    assert listed.status_code == 200
    body = listed.json()
    server = next(s for s in body["servers"] if s["name"] == "context7")
    assert server["source"] == SOURCE_SHEJANE
    assert server["env_keys"] == ["CONTEXT7_API_KEY"]
    assert "secret-value" not in json.dumps(body)

    deleted = client.delete(
        "/local/v1/mcp-servers/context7",
        headers={"Authorization": "Bearer tok"},
    )
    assert deleted.status_code == 200
    raw = json.loads(config_path.read_text(encoding="utf-8"))
    assert "context7" not in raw.get("mcpServers", {})


# ---------------------------------------------------------------------------
# build_agent — mcp_enabled gate
# ---------------------------------------------------------------------------


def test_build_agent_skips_mcp_when_disabled(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """When `mcp_enabled=False`, `build_tools` MUST be called with
    `include_mcp=False`. We pin this via a registry spy rather than
    introspecting compiled-agent state — same pattern as
    test_build_agent_excludes_memory_search_when_disabled.
    """
    from langgraph.store.memory import InMemoryStore

    import local_host.agent.builder as builder_mod
    from local_host.agent.builder import build_agent, open_checkpointer
    from local_host.store.sqlite import LocalStore

    captured: dict[str, object] = {}

    async def fake_build_tools(**kwargs):
        captured.update(kwargs)
        return []

    def fake_create_deep_agent(**kwargs):
        return object()

    monkeypatch.setattr(builder_mod, "build_tools", fake_build_tools)
    monkeypatch.setattr(builder_mod, "create_deep_agent", fake_create_deep_agent)

    async def run() -> bool:
        reset_settings_for_tests(data_dir=tmp_path)
        monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
        store = await LocalStore.open(tmp_path / "store.db")
        saver, stack = await open_checkpointer()
        try:
            await build_agent(
                store=store,
                checkpointer=saver,
                agent_store=InMemoryStore(),
                workspace_root=str(tmp_path),
                run_id="r-mcp-off",
                mcp_enabled=False,
            )
            return captured.get("include_mcp") is False
        finally:
            await store.close()
            await stack.aclose()

    assert asyncio.run(run()) is True


# ---------------------------------------------------------------------------
# Per-server disable — `mcp_disabled_servers` propagates to build_mcp_tools
# ---------------------------------------------------------------------------


def test_build_mcp_tools_drops_disabled_names_before_client(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`disabled_servers` must filter config before any connection opens."""
    import local_host.tools.mcp as mcp_mod

    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps(
            {
                "mcpServers": {
                    "keep": {"command": "node", "args": ["k.js"]},
                    "drop": {"command": "node", "args": ["d.js"]},
                }
            }
        ),
    )

    captured_config: dict[str, dict] = {}

    async def fake_build(config):
        captured_config.update(config)
        return []

    monkeypatch.setattr(mcp_mod, "_build_mcp_tools_from_config", fake_build)

    asyncio.run(mcp_mod.build_mcp_tools(tmp_path, disabled_servers={"drop"}))
    assert "keep" in captured_config
    assert "drop" not in captured_config


def test_build_mcp_tools_empty_after_disable_returns_early(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """If every discovered server is in `disabled_servers`, we should
    short-circuit and NOT even import MultiServerMCPClient — the
    early-return on empty config covers this."""
    import local_host.tools.mcp as mcp_mod

    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"only": {"command": "node"}}),
    )

    called: dict[str, bool] = {"yes": False}

    class FakeClient:
        def __init__(self, *a, **kw):
            called["yes"] = True

        async def get_tools(self):
            return []

    import langchain_mcp_adapters.client as mcp_client_mod

    monkeypatch.setattr(mcp_client_mod, "MultiServerMCPClient", FakeClient)

    tools = asyncio.run(mcp_mod.build_mcp_tools(tmp_path, disabled_servers={"only"}))
    assert tools == []
    assert called["yes"] is False


def test_mcp_discovery_stops_after_bounded_candidates(monkeypatch: pytest.MonkeyPatch) -> None:
    import langchain_mcp_adapters.sessions as sessions_mod
    from mcp.types import ListToolsResult, Tool

    import local_host.tools.mcp as mcp_mod

    pages = 0

    class FakeSession:
        async def initialize(self) -> None:
            return None

        async def list_tools(self, cursor=None):
            nonlocal pages
            pages += 1
            start = (pages - 1) * 40
            return ListToolsResult(
                tools=[
                    Tool(
                        name=f"tool_{index}",
                        description="Bounded test tool.",
                        inputSchema={"type": "object", "properties": {}},
                    )
                    for index in range(start, start + 40)
                ],
                nextCursor=f"page-{pages + 1}",
            )

    @asynccontextmanager
    async def fake_create_session(_connection):
        yield FakeSession()

    monkeypatch.setattr(sessions_mod, "create_session", fake_create_session)
    tools = asyncio.run(
        mcp_mod._build_mcp_tools_from_config(
            {"server": {"transport": "stdio", "command": "unused"}}
        )
    )

    assert pages == 2
    assert len(tools) == mcp_mod.MAX_MCP_TOOLS


def test_mcp_websocket_discovery_is_rejected(monkeypatch: pytest.MonkeyPatch) -> None:
    import langchain_mcp_adapters.sessions as sessions_mod

    import local_host.tools.mcp as mcp_mod

    @asynccontextmanager
    async def unexpected_session(_connection):
        raise AssertionError("websocket connection should not open")
        yield

    monkeypatch.setattr(sessions_mod, "create_session", unexpected_session)
    tools = asyncio.run(
        mcp_mod._build_mcp_tools_from_config(
            {"remote": {"transport": "websocket", "url": "wss://example.com/mcp"}}
        )
    )
    assert tools == []


@pytest.mark.parametrize("alias", ["http", "streamable-http"])
def test_mcp_http_aliases_receive_bounded_client(
    alias: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    import langchain_mcp_adapters.sessions as sessions_mod
    from mcp.types import ListToolsResult

    import local_host.tools.mcp as mcp_mod

    captured: dict[str, object] = {}

    class FakeSession:
        async def initialize(self) -> None:
            return None

        async def list_tools(self, cursor=None):
            return ListToolsResult(tools=[])

    @asynccontextmanager
    async def fake_create_session(connection):
        captured.update(connection)
        yield FakeSession()

    monkeypatch.setattr(sessions_mod, "create_session", fake_create_session)
    asyncio.run(
        mcp_mod._build_mcp_tools_from_config(
            {"remote": {"transport": alias, "url": "https://example.com/mcp"}}
        )
    )
    assert captured["httpx_client_factory"] is mcp_mod._bounded_http_client


def test_build_agent_threads_disabled_set_to_mcp_loader(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Disabled MCP names must reach the attempt-local MCP loader."""
    from langgraph.store.memory import InMemoryStore

    import local_host.agent.builder as builder_mod
    from local_host.agent.builder import build_agent, open_checkpointer
    from local_host.store.sqlite import LocalStore

    captured: dict[str, object] = {}

    async def fake_build_tools(**kwargs):
        return []

    async def fake_build_validated_mcp_tools(_data_dir, **kwargs):
        captured.update(kwargs)
        return []

    def fake_create_deep_agent(**kwargs):
        return object()

    monkeypatch.setattr(builder_mod, "build_tools", fake_build_tools)
    monkeypatch.setattr(
        builder_mod,
        "build_validated_mcp_tools",
        fake_build_validated_mcp_tools,
    )
    monkeypatch.setattr(builder_mod, "create_deep_agent", fake_create_deep_agent)

    async def run() -> set[str] | None:
        reset_settings_for_tests(data_dir=tmp_path)
        monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
        store = await LocalStore.open(tmp_path / "store.db")
        saver, stack = await open_checkpointer()
        try:
            await build_agent(
                store=store,
                checkpointer=saver,
                agent_store=InMemoryStore(),
                workspace_root=str(tmp_path),
                run_id="r-disabled",
                mcp_enabled=True,
                mcp_disabled_servers={"github", "playwright"},
            )
            return captured.get("disabled_servers")  # type: ignore[return-value]
        finally:
            await store.close()
            await stack.aclose()

    result = asyncio.run(run())
    assert result == {"github", "playwright"}
