"""Tests for Runtime-owned MCP configuration, catalog, and gating.

The autouse fixture in `conftest.py` disables disk scanning by
default. Tests in this file re-enable it via
`monkeypatch.setenv("SHEJANE_LOCAL_MCP_DISCOVERY", "on")` and point
`HOME` at a tmp_path so the scan finds only fixture files instead of
the developer's Runtime configuration.
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
import tempfile
from contextlib import asynccontextmanager
from pathlib import Path

import pytest
from fastapi.testclient import TestClient
from mcp.client.stdio import StdioServerParameters

from local_host.config import reset_settings_for_tests
from local_host.server import create_app
from local_host.store.sqlite import LocalStore
from local_host.tools.mcp import (
    MAX_MCP_DESCRIPTION_CHARS,
    MAX_MCP_SCHEMA_DEPTH,
    SOURCE_ENV,
    SOURCE_SHEJANE,
    MCPToolCatalog,
    _normalize_entry,
    discover_servers,
    mcp_sensitive_values,
    validate_mcp_tools,
)
from local_host.tools.mcp_stdio import MCPStdioFrameTooLargeError, bounded_stdio_client


@pytest.mark.asyncio
async def test_stdio_frame_limit_rejects_before_json_parsing() -> None:
    server = StdioServerParameters(
        command=sys.executable,
        args=["-c", "print('x' * 128, flush=True)"],
    )
    async with bounded_stdio_client(server, max_frame_bytes=32) as (read, _write):
        result = await read.receive()
    assert isinstance(result, MCPStdioFrameTooLargeError)


def _isolate_home(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    """Re-enable disk scan + redirect HOME so discovery only sees
    what THIS test wrote. Returns the fake home for convenience."""
    monkeypatch.setenv("SHEJANE_LOCAL_MCP_DISCOVERY", "on")
    monkeypatch.setenv("HOME", str(tmp_path))
    # macOS-only fallback for Path.home() — older Python honors $HOME
    # first, but we set it anyway for belt-and-suspenders.
    monkeypatch.delenv("USERPROFILE", raising=False)
    return tmp_path


# ---------------------------------------------------------------------------
# _normalize_entry — schema sanity
# ---------------------------------------------------------------------------


def test_normalize_stdio_default_transport() -> None:
    norm = _normalize_entry("fs", {"command": "npx", "args": ["-y", "fs-mcp"]})
    assert norm is not None
    assert norm["transport"] == "stdio"
    assert norm["command"] == "npx"
    assert norm["args"] == ["-y", "fs-mcp"]


def test_normalize_http_url_infers_streamable_http() -> None:
    norm = _normalize_entry("remote", {"url": "https://api.example.com/mcp"})
    assert norm is not None
    assert norm["transport"] == "streamable_http"
    assert norm["url"] == "https://api.example.com/mcp"


def test_normalize_websocket_url_infers_ws_transport() -> None:
    norm = _normalize_entry("rt", {"url": "wss://realtime.example.com"})
    assert norm is not None
    assert norm["transport"] == "websocket"


def test_normalize_explicit_transport_wins() -> None:
    norm = _normalize_entry("x", {"transport": "sse", "url": "https://api.example.com/sse"})
    assert norm is not None
    assert norm["transport"] == "sse"


@pytest.mark.parametrize("alias", ["http", "streamable-http"])
def test_normalize_http_transport_aliases(alias: str) -> None:
    norm = _normalize_entry(
        "remote",
        {"transport": alias, "url": "https://api.example.com/mcp"},
    )
    assert norm is not None
    assert norm["transport"] == "streamable_http"


def test_normalize_missing_command_and_url_returns_none() -> None:
    # Incomplete entries should be dropped instead of crashing later.
    assert _normalize_entry("x", {"args": ["foo"]}) is None


def test_normalize_disabled_flag_returns_none() -> None:
    # Manually managed config may explicitly mark an entry disabled.
    assert _normalize_entry("x", {"command": "npx", "disabled": True}) is None


def test_normalize_coerces_args_to_strings() -> None:
    # Some users (or autogenerated configs) pass ints; subprocess
    # would crash on those without coercion.
    norm = _normalize_entry("x", {"command": "node", "args": ["server.js", 8080]})
    assert norm is not None
    assert norm["args"] == ["server.js", "8080"]


def test_normalize_strips_nested_env_values() -> None:
    # Env values must be strings — drop dicts/lists silently.
    norm = _normalize_entry(
        "x",
        {
            "command": "node",
            "env": {"KEY": "value", "BAD": {"nested": 1}, "NULL_VAL": None},
        },
    )
    assert norm is not None
    assert norm["env"] == {"KEY": "value"}


def test_normalize_non_dict_returns_none() -> None:
    assert _normalize_entry("x", "not a dict") is None
    assert _normalize_entry("x", None) is None


def test_mcp_metadata_rejects_configured_secret(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from langchain_core.tools import tool

    secret = "secret-value-12345"
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps(
            {
                "remote": {
                    "url": "https://example.com/mcp",
                    "headers": {"Authorization": f"Bearer {secret}"},
                }
            }
        ),
    )

    @tool("mcp.remote.leak")
    def leaking_tool(value: str = secret) -> str:
        """A tool whose server-controlled schema echoes a credential."""
        return value

    sensitive = mcp_sensitive_values(tmp_path)
    assert any(secret in value for value in sensitive)
    assert validate_mcp_tools([leaking_tool], sensitive_values=sensitive) == []

    @tool(secret)
    def leaking_name(value: str) -> str:
        """A tool whose name echoes a credential."""
        return value

    assert (
        validate_mcp_tools(
            [leaking_name],
            sensitive_values=sensitive,
        )
        == []
    )


def test_mcp_metadata_enforces_size_depth_and_name_boundaries() -> None:
    from langchain_core.tools import tool

    @tool("mcp.safe.lookup")
    def safe_tool(value: str) -> str:
        """Look up one value."""
        return value

    @tool("mcp.too.large", description="x" * (MAX_MCP_DESCRIPTION_CHARS + 1))
    def large_tool(value: str) -> str:
        return value

    deep_schema: dict[str, object] = {"type": "object"}
    cursor = deep_schema
    for _ in range(MAX_MCP_SCHEMA_DEPTH + 1):
        child: dict[str, object] = {}
        cursor["properties"] = child
        cursor = child

    accepted = validate_mcp_tools(
        [safe_tool, large_tool, safe_tool],
        reserved_names={"mcp.reserved"},
    )
    assert [item.name for item in accepted] == ["mcp.safe.lookup"]
    assert accepted[0].args_schema["type"] == "object"
    assert (
        validate_mcp_tools(
            [safe_tool],
            reserved_names={"mcp.safe.lookup"},
        )
        == []
    )
    safe_tool.args_schema = deep_schema
    assert validate_mcp_tools([safe_tool]) == []


@pytest.mark.asyncio
async def test_runtime_catalog_reuses_tools_until_server_config_changes(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import langchain_mcp_adapters.sessions as sessions_mod
    from mcp.types import ListToolsResult, Tool

    sessions_opened = 0

    class FakeSession:
        async def initialize(self) -> None:
            return None

        async def list_tools(self, cursor=None):
            return ListToolsResult(
                tools=[
                    Tool(
                        name="lookup",
                        description="Look up one value.",
                        inputSchema={"type": "object", "properties": {}},
                    )
                ]
            )

    @asynccontextmanager
    async def fake_create_session(_connection):
        nonlocal sessions_opened
        sessions_opened += 1
        yield FakeSession()

    monkeypatch.setattr(sessions_mod, "create_session", fake_create_session)
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"docs": {"command": "node", "args": ["server-v1.js"]}}),
    )
    catalog = MCPToolCatalog(tmp_path)

    first = await catalog.get_tools()
    second = await catalog.get_tools()

    assert [item.name for item in first] == ["docs_lookup"]
    assert [item.name for item in second] == ["docs_lookup"]
    assert sessions_opened == 1

    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"docs": {"command": "node", "args": ["server-v2.js"]}}),
    )
    await catalog.get_tools()

    assert sessions_opened == 2

    monkeypatch.setenv("SHEJANE_LOCAL_MCP_SERVERS", "{}")
    await catalog.get_tools()
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"docs": {"command": "node", "args": ["server-v2.js"]}}),
    )
    await catalog.get_tools()

    assert sessions_opened == 3
    await catalog.close()


@pytest.mark.asyncio
async def test_runtime_catalog_refreshes_changed_servers_concurrently(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import local_host.tools.mcp as mcp_mod

    active = 0
    peak_active = 0
    discovered: list[str] = []

    async def fake_open(server_name, _connection):
        nonlocal active, peak_active
        active += 1
        peak_active = max(peak_active, active)
        discovered.append(server_name)
        await asyncio.sleep(0)
        active -= 1
        return None, (), None

    monkeypatch.setattr(mcp_mod, "_open_mcp_server", fake_open)
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps(
            {
                "docs": {"command": "node", "args": ["docs.js"]},
                "github": {"command": "node", "args": ["github.js"]},
            }
        ),
    )

    catalog = MCPToolCatalog(tmp_path)
    await catalog.get_tools()

    assert set(discovered) == {"docs", "github"}
    assert peak_active == 2
    await catalog.close()


@pytest.mark.asyncio
async def test_runtime_catalog_reuses_one_live_session_for_tool_calls(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import langchain_mcp_adapters.sessions as sessions_mod
    from mcp.types import CallToolResult, ListToolsResult, TextContent, Tool

    sessions_opened = 0
    sessions_closed = 0
    calls = 0

    class FakeSession:
        async def initialize(self) -> None:
            return None

        async def list_tools(self, cursor=None):
            return ListToolsResult(
                tools=[
                    Tool(
                        name="lookup",
                        description="Look up one value.",
                        inputSchema={"type": "object", "properties": {}},
                    )
                ]
            )

        async def call_tool(self, name, arguments, **kwargs):
            nonlocal calls
            calls += 1
            return CallToolResult(content=[TextContent(type="text", text=f"{name}:ok")])

    @asynccontextmanager
    async def fake_create_session(_connection):
        nonlocal sessions_opened, sessions_closed
        sessions_opened += 1
        try:
            yield FakeSession()
        finally:
            sessions_closed += 1

    monkeypatch.setattr(sessions_mod, "create_session", fake_create_session)
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"docs": {"command": "node", "args": ["server.js"]}}),
    )
    catalog = MCPToolCatalog(tmp_path)

    await catalog.get_tools()
    async with catalog.acquire_tools() as tools:
        await tools[0].tool.ainvoke({})
        await tools[0].tool.ainvoke({})

    assert sessions_opened == 1
    assert sessions_closed == 0
    assert calls == 2

    assert await catalog.get_tools(disabled_servers={"docs"}) == []
    assert sessions_closed == 1
    await catalog.close()
    assert sessions_closed == 1


@pytest.mark.asyncio
async def test_runtime_catalog_keeps_retired_session_until_snapshot_release(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import langchain_mcp_adapters.sessions as sessions_mod
    from mcp.types import CallToolResult, ListToolsResult, TextContent, Tool

    sessions_closed = 0

    class FakeSession:
        async def initialize(self) -> None:
            return None

        async def list_tools(self, cursor=None):
            return ListToolsResult(
                tools=[
                    Tool(
                        name="lookup",
                        description="Look up one value.",
                        inputSchema={"type": "object", "properties": {}},
                    )
                ]
            )

        async def call_tool(self, name, arguments, **kwargs):
            return CallToolResult(content=[TextContent(type="text", text=f"{name}:ok")])

    @asynccontextmanager
    async def fake_create_session(_connection):
        nonlocal sessions_closed
        try:
            yield FakeSession()
        finally:
            sessions_closed += 1

    monkeypatch.setattr(sessions_mod, "create_session", fake_create_session)
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"docs": {"command": "node", "args": ["server.js"]}}),
    )
    catalog = MCPToolCatalog(tmp_path)

    await catalog.get_tools()
    async with catalog.acquire_tools() as tools:
        await catalog.invalidate("docs")
        assert sessions_closed == 0
        await tools[0].tool.ainvoke({})

    assert sessions_closed == 1
    await catalog.close()


@pytest.mark.asyncio
async def test_runtime_catalog_refreshes_after_tools_list_changed_notification(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import langchain_mcp_adapters.sessions as sessions_mod
    from mcp.types import (
        CallToolResult,
        ListToolsResult,
        ServerNotification,
        TextContent,
        Tool,
        ToolListChangedNotification,
    )

    sessions_opened = 0
    sessions_closed = 0
    message_handlers = []

    class FakeSession:
        def __init__(self, session_id: int) -> None:
            self.session_id = session_id

        async def initialize(self) -> None:
            return None

        async def list_tools(self, cursor=None):
            return ListToolsResult(
                tools=[
                    Tool(
                        name="lookup",
                        description=f"Look up with session {self.session_id}.",
                        inputSchema={"type": "object", "properties": {}},
                    )
                ]
            )

        async def call_tool(self, name, arguments, **kwargs):
            return CallToolResult(
                content=[TextContent(type="text", text=f"{name}:{self.session_id}")]
            )

    @asynccontextmanager
    async def fake_create_session(connection):
        nonlocal sessions_opened, sessions_closed
        sessions_opened += 1
        message_handlers.append(connection["session_kwargs"]["message_handler"])
        try:
            yield FakeSession(sessions_opened)
        finally:
            sessions_closed += 1

    monkeypatch.setattr(sessions_mod, "create_session", fake_create_session)
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"docs": {"command": "node", "args": ["server.js"]}}),
    )
    catalog = MCPToolCatalog(tmp_path)

    await catalog.get_tools()
    async with catalog.acquire_tools() as first_run_tools:
        await message_handlers[0](ServerNotification(root=ToolListChangedNotification()))
        for _ in range(20):
            await asyncio.sleep(0)
            if sessions_opened == 2:
                break

        assert sessions_opened == 2
        assert sessions_closed == 0
        result = await first_run_tools[0].tool.ainvoke({})
        assert result[0]["text"] == "lookup:1"

    assert sessions_closed == 1
    async with catalog.acquire_tools() as second_run_tools:
        assert "session 2" in second_run_tools[0].description

    await catalog.close()
    assert sessions_closed == 2


@pytest.mark.asyncio
async def test_runtime_catalog_retries_failed_server_after_backoff(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import local_host.tools.mcp as mcp_mod

    now = 100.0
    attempts = 0
    stopped = 0

    class FakeSupervisor:
        async def stop(self):
            nonlocal stopped
            stopped += 1

    async def fake_open(_server_name, _connection):
        nonlocal attempts
        attempts += 1
        if attempts == 1:
            return None, (), "TimeoutError"
        return FakeSupervisor(), (), None

    monkeypatch.setattr(mcp_mod, "_open_mcp_server", fake_open)
    monkeypatch.setattr(mcp_mod.time, "monotonic", lambda: now)
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"docs": {"command": "node", "args": ["server.js"]}}),
    )
    catalog = MCPToolCatalog(tmp_path)

    await catalog.get_tools()
    await catalog.get_tools()
    assert attempts == 1
    assert catalog.server_statuses()["docs"]["status"] == "error"

    now += mcp_mod.MCP_RETRY_BACKOFF_SECONDS
    await catalog.get_tools()
    assert attempts == 2
    assert catalog.server_statuses()["docs"]["status"] == "ready"

    await catalog.close()
    assert stopped == 1


@pytest.mark.asyncio
async def test_mcp_catalog_metadata_persists_without_credentials(tmp_path: Path) -> None:
    store = await LocalStore.open(tmp_path / "store.db")
    try:
        saved = await store.upsert_mcp_catalog(
            server_name="docs",
            config_fingerprint="fingerprint-v1",
            tools=[
                {
                    "name": "docs_lookup",
                    "raw_name": "lookup",
                    "description": "Look up documentation.",
                    "args_schema": {"type": "object", "properties": {}},
                }
            ],
            status="ready",
            error_type=None,
        )
        loaded = await store.get_mcp_catalog("docs")

        assert loaded == saved
        assert loaded["version"] == 1
        assert loaded["tools"][0]["raw_name"] == "lookup"
        assert "credential" not in json.dumps(loaded).lower()

        failed = await store.upsert_mcp_catalog(
            server_name="docs",
            config_fingerprint="fingerprint-v1",
            tools=loaded["tools"],
            status="error",
            error_type="TimeoutError",
        )
        assert failed["version"] == 2
        assert failed["last_success_at"] == loaded["last_success_at"]

        await store.delete_mcp_catalog("docs")
        assert await store.get_mcp_catalog("docs") is None
    finally:
        await store.close()


@pytest.mark.asyncio
async def test_runtime_catalog_persists_successful_tool_metadata(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from langchain_core.tools import tool

    import local_host.tools.mcp as mcp_mod

    @tool("docs_lookup")
    async def lookup(query: str) -> str:
        """Look up documentation."""
        return query

    class FakeSupervisor:
        async def stop(self):
            return None

    async def fake_open(_server_name, _connection):
        return FakeSupervisor(), (lookup,), None

    monkeypatch.setattr(mcp_mod, "_open_mcp_server", fake_open)
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"docs": {"command": "node", "args": ["server.js"]}}),
    )
    store = await LocalStore.open(tmp_path / "store.db")
    catalog = MCPToolCatalog(tmp_path, store=store)
    try:
        await catalog.get_tools()
        persisted = await store.get_mcp_catalog("docs")
        assert persisted is not None
        assert persisted["status"] == "ready"
        assert persisted["tools"] == [
            {
                "args_schema": lookup.tool_call_schema.model_json_schema(),
                "description": "Look up documentation.",
                "name": "docs_lookup",
                "raw_name": "lookup",
            }
        ]
    finally:
        await catalog.close()
        await store.close()


@pytest.mark.asyncio
async def test_runtime_catalog_hydrates_without_connecting_server(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import local_host.tools.mcp as mcp_mod

    config = {"command": "node", "args": ["server.js"], "transport": "stdio"}
    monkeypatch.setenv("SHEJANE_LOCAL_MCP_SERVERS", json.dumps({"docs": config}))
    store = await LocalStore.open(tmp_path / "store.db")
    await store.upsert_mcp_catalog(
        server_name="docs",
        config_fingerprint=mcp_mod._mcp_config_fingerprint(config),
        tools=[
            {
                "name": "docs_lookup",
                "raw_name": "lookup",
                "description": "Look up documentation.",
                "args_schema": {"type": "object", "properties": {}},
            }
        ],
        status="ready",
        error_type=None,
    )

    connections = 0

    class FakeSupervisor:
        async def stop(self):
            return None

    async def fake_open(_server_name, _connection):
        nonlocal connections
        connections += 1
        return FakeSupervisor(), (), None

    monkeypatch.setattr(mcp_mod, "_open_mcp_server", fake_open)
    catalog = MCPToolCatalog(tmp_path, store=store)
    try:
        await catalog.hydrate()
        assert connections == 0
        async with catalog.acquire_tools() as tools:
            assert [item.name for item in tools] == ["docs_lookup"]
        assert catalog.server_statuses()["docs"]["status"] == "idle"
        assert catalog._refresh_task is not None
        await asyncio.wait_for(asyncio.shield(catalog._refresh_task), timeout=0.1)
        assert connections == 1
        assert catalog.server_statuses()["docs"]["status"] == "ready"
    finally:
        await catalog.close()
        await store.close()


@pytest.mark.asyncio
async def test_run_snapshot_does_not_wait_for_first_mcp_discovery(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    import local_host.tools.mcp as mcp_mod

    started = asyncio.Event()
    release = asyncio.Event()

    async def slow_open(_server_name, _connection):
        started.set()
        await release.wait()
        return None, (), "TimeoutError"

    monkeypatch.setattr(mcp_mod, "_open_mcp_server", slow_open)
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"docs": {"command": "node", "args": ["server.js"]}}),
    )
    catalog = MCPToolCatalog(tmp_path)
    try:
        async with asyncio.timeout(0.1):
            async with catalog.acquire_tools() as tools:
                assert tools == []
        await asyncio.wait_for(started.wait(), timeout=0.1)
    finally:
        release.set()
        await catalog.close()


@pytest.mark.asyncio
async def test_background_discovery_is_visible_to_the_next_run(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from langchain_core.tools import tool

    import local_host.tools.mcp as mcp_mod

    discovered = asyncio.Event()

    @tool("docs_lookup")
    async def lookup(query: str) -> str:
        """Look up documentation."""
        return query

    class FakeSupervisor:
        async def stop(self):
            return None

    async def fake_open(_server_name, _connection):
        discovered.set()
        return FakeSupervisor(), (lookup,), None

    monkeypatch.setattr(mcp_mod, "_open_mcp_server", fake_open)
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"docs": {"command": "node", "args": ["server.js"]}}),
    )
    catalog = MCPToolCatalog(tmp_path)
    try:
        async with catalog.acquire_tools() as first:
            assert first == []
        await asyncio.wait_for(discovered.wait(), timeout=0.1)
        assert catalog._refresh_task is not None
        await asyncio.wait_for(asyncio.shield(catalog._refresh_task), timeout=0.1)
        async with catalog.acquire_tools() as second:
            assert [item.name for item in second] == ["docs_lookup"]
    finally:
        await catalog.close()


# ---------------------------------------------------------------------------
# discover_servers — disk scan gate
# ---------------------------------------------------------------------------


def test_discover_skips_disk_when_flag_off(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    # conftest sets DISCOVERY=off by default. Without an env var, we
    # get nothing — even though we'd be scanning the real home dir.
    monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
    out = discover_servers(tmp_path)
    assert out == []


def test_discover_env_override_works_even_when_disk_off(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # Env var is the explicit-config path and must work regardless of
    # the disk-scan flag — useful for tests + one-off debugging.
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"e": {"command": "node", "args": ["e.js"]}}),
    )
    out = discover_servers(tmp_path)
    assert len(out) == 1
    assert out[0].name == "e"
    assert out[0].source == SOURCE_ENV
    assert out[0].config["transport"] == "stdio"


def test_discover_env_accepts_mcpservers_wrapper(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"mcpServers": {"e": {"command": "node"}}}),
    )
    out = discover_servers(tmp_path)
    assert [s.name for s in out] == ["e"]


def test_discover_malformed_env_logged_and_skipped(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("SHEJANE_LOCAL_MCP_SERVERS", "{not valid json")
    out = discover_servers(tmp_path)
    assert out == []


# ---------------------------------------------------------------------------
# discover_servers — multi-source disk scan
# ---------------------------------------------------------------------------


def test_discover_reads_shejane_user_config(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    home = _isolate_home(monkeypatch, tmp_path)
    monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
    shejane_dir = home / ".shejane"
    shejane_dir.mkdir(parents=True, exist_ok=True)
    (shejane_dir / "mcp-servers.json").write_text(
        json.dumps({"mcpServers": {"local-fs": {"command": "npx", "args": ["fs"]}}}),
        encoding="utf-8",
    )
    out = discover_servers(tmp_path)
    names = [s.name for s in out]
    assert "local-fs" in names
    fs = next(s for s in out if s.name == "local-fs")
    assert fs.source == SOURCE_SHEJANE
    assert "mcp-servers.json" in fs.source_path


def test_discover_does_not_activate_other_clients_global_servers(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    home = _isolate_home(monkeypatch, tmp_path)
    monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
    cursor_dir = home / ".cursor"
    cursor_dir.mkdir(parents=True)
    (cursor_dir / "mcp.json").write_text(
        json.dumps({"mcpServers": {"cursor-server": {"command": "cursor-mcp"}}}),
        encoding="utf-8",
    )
    codex_dir = home / ".codex"
    codex_dir.mkdir(parents=True)
    (codex_dir / "config.toml").write_text(
        '[mcp_servers.codex-server]\ncommand = "codex-mcp"\n',
        encoding="utf-8",
    )

    assert discover_servers(tmp_path) == []


def test_discover_malformed_disk_file_skipped(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    home = _isolate_home(monkeypatch, tmp_path)
    monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
    shejane_dir = home / ".shejane"
    shejane_dir.mkdir(parents=True, exist_ok=True)
    (shejane_dir / "mcp-servers.json").write_text("{ not json", encoding="utf-8")
    # Should not raise — just no entries from this source.
    out = discover_servers(tmp_path)
    assert all(s.source != SOURCE_SHEJANE for s in out)


# ---------------------------------------------------------------------------
# HTTP — GET /local/v1/mcp-servers
# ---------------------------------------------------------------------------


@pytest.fixture
def client(monkeypatch: pytest.MonkeyPatch) -> TestClient:
    """Spin up the daemon with an isolated tmp data dir + tok auth.

    Doesn't enable disk scan — tests that want disk scan flip the
    SHEJANE_LOCAL_MCP_DISCOVERY env per test body.
    """
    tmp = Path(tempfile.mkdtemp(prefix="jdl-mcp-"))
    os.environ["SHEJANE_LOCAL_HOST_TOKEN"] = "tok"
    settings = reset_settings_for_tests(
        SHEJANE_LOCAL_HOST_ADDR="127.0.0.1",
        SHEJANE_LOCAL_HOST_PORT=17371,
        SHEJANE_LOCAL_HOST_TOKEN="tok",
        data_dir=tmp,
    )
    app = create_app(settings)
    with TestClient(app) as c:
        yield c


def test_http_mcp_servers_empty_default(client: TestClient) -> None:
    # autouse fixture disables disk scan; no env var; expect 0 servers
    # but sources_scanned still populated so UI can hint user where to
    # drop configs.
    r = client.get("/local/v1/mcp-servers", headers={"Authorization": "Bearer tok"})
    assert r.status_code == 200
    body = r.json()
    assert body["servers"] == []
    # Always-present source labels regardless of scan toggle
    assert "env" in body["sources_scanned"]
    assert "shejane" in body["sources_scanned"]


def test_http_mcp_servers_lists_env_entries(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    class FakeCatalog:
        def server_statuses(self):
            return {
                "github": {
                    "status": "error",
                    "tool_count": 0,
                    "error_type": "TimeoutError",
                }
            }

    client.app.state.mcp_catalog = FakeCatalog()
    # Setting the env var should produce one normalized server row.
    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps(
            {
                "mcpServers": {
                    "github": {
                        "command": "npx",
                        "args": ["-y", "@modelcontextprotocol/server-github"],
                        "env": {"GITHUB_TOKEN": "ghp_secret_value"},
                    }
                }
            }
        ),
    )
    r = client.get("/local/v1/mcp-servers", headers={"Authorization": "Bearer tok"})
    assert r.status_code == 200
    body = r.json()
    assert len(body["servers"]) == 1
    s = body["servers"][0]
    assert s["name"] == "github"
    assert s["transport"] == "stdio"
    assert s["source"] == "env"
    assert s["command"] == "npx"
    assert s["args"] == ["-y", "@modelcontextprotocol/server-github"]
    assert s["status"] == "error"
    assert s["tool_count"] == 0
    assert s["error_type"] == "TimeoutError"
    # SECURITY: env *keys* surface, env *values* MUST NOT.
    assert s["env_keys"] == ["GITHUB_TOKEN"]
    assert "ghp_secret_value" not in json.dumps(body)


def test_http_mcp_server_crud_writes_only_shejane_config(
    client: TestClient, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    home = _isolate_home(monkeypatch, tmp_path)
    invalidated: list[str | None] = []

    class RecordingCatalog:
        def server_statuses(self):
            return {}

        def request_refresh(self):
            return None

        async def invalidate(self, server_name=None):
            invalidated.append(server_name)

    client.app.state.mcp_catalog = RecordingCatalog()
    payload = {
        "name": "context7",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@upstash/context7-mcp"],
        "env": {"CONTEXT7_API_KEY": "secret-value"},
    }

    created = client.post(
        "/local/v1/mcp-servers",
        headers={"Authorization": "Bearer tok"},
        json=payload,
    )
    assert created.status_code == 200, created.text
    assert created.json()["server"]["name"] == "context7"

    config_path = home / ".shejane" / "mcp-servers.json"
    raw = json.loads(config_path.read_text(encoding="utf-8"))
    assert raw["mcpServers"]["context7"]["command"] == "npx"
    assert raw["mcpServers"]["context7"]["env"]["CONTEXT7_API_KEY"] == "secret-value"

    listed = client.get("/local/v1/mcp-servers", headers={"Authorization": "Bearer tok"})
    assert listed.status_code == 200
    body = listed.json()
    server = next(s for s in body["servers"] if s["name"] == "context7")
    assert server["source"] == SOURCE_SHEJANE
    assert server["env_keys"] == ["CONTEXT7_API_KEY"]
    assert "secret-value" not in json.dumps(body)

    deleted = client.delete(
        "/local/v1/mcp-servers/context7",
        headers={"Authorization": "Bearer tok"},
    )
    assert deleted.status_code == 200
    raw = json.loads(config_path.read_text(encoding="utf-8"))
    assert "context7" not in raw.get("mcpServers", {})
    assert invalidated == ["context7", "context7"]


# ---------------------------------------------------------------------------
# build_agent — mcp_enabled gate
# ---------------------------------------------------------------------------


def test_build_agent_skips_mcp_when_disabled(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """When `mcp_enabled=False`, P6 must not read the MCP catalog."""
    from langgraph.store.memory import InMemoryStore

    import local_host.agent.builder as builder_mod
    from local_host.agent.builder import build_agent, open_checkpointer
    from local_host.store.sqlite import LocalStore

    catalog_reads = 0

    async def fake_build_tools(**kwargs):
        return []

    class FakeCatalog:
        async def get_tools(self, **kwargs):
            nonlocal catalog_reads
            catalog_reads += 1
            return []

    def fake_create_deep_agent(**kwargs):
        return object()

    monkeypatch.setattr(builder_mod, "build_tools", fake_build_tools)
    monkeypatch.setattr(builder_mod, "create_deep_agent", fake_create_deep_agent)

    async def run() -> bool:
        reset_settings_for_tests(data_dir=tmp_path)
        monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
        store = await LocalStore.open(tmp_path / "store.db")
        saver, stack = await open_checkpointer()
        try:
            await build_agent(
                store=store,
                checkpointer=saver,
                agent_store=InMemoryStore(),
                workspace_root=str(tmp_path),
                run_id="r-mcp-off",
                mcp_enabled=False,
                mcp_catalog=FakeCatalog(),
            )
            return catalog_reads == 0
        finally:
            await store.close()
            await stack.aclose()

    assert asyncio.run(run()) is True


# ---------------------------------------------------------------------------
# Direct MCP loader behavior
# ---------------------------------------------------------------------------


def test_build_mcp_tools_drops_disabled_names_before_client(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`disabled_servers` must filter config before any connection opens."""
    import local_host.tools.mcp as mcp_mod

    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps(
            {
                "mcpServers": {
                    "keep": {"command": "node", "args": ["k.js"]},
                    "drop": {"command": "node", "args": ["d.js"]},
                }
            }
        ),
    )

    captured_config: dict[str, dict] = {}

    async def fake_build(config):
        captured_config.update(config)
        return []

    monkeypatch.setattr(mcp_mod, "_build_mcp_tools_from_config", fake_build)

    asyncio.run(mcp_mod.build_mcp_tools(tmp_path, disabled_servers={"drop"}))
    assert "keep" in captured_config
    assert "drop" not in captured_config


def test_build_mcp_tools_empty_after_disable_returns_early(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """If every discovered server is in `disabled_servers`, we should
    short-circuit and NOT even import MultiServerMCPClient — the
    early-return on empty config covers this."""
    import local_host.tools.mcp as mcp_mod

    monkeypatch.setenv(
        "SHEJANE_LOCAL_MCP_SERVERS",
        json.dumps({"only": {"command": "node"}}),
    )

    called: dict[str, bool] = {"yes": False}

    class FakeClient:
        def __init__(self, *a, **kw):
            called["yes"] = True

        async def get_tools(self):
            return []

    import langchain_mcp_adapters.client as mcp_client_mod

    monkeypatch.setattr(mcp_client_mod, "MultiServerMCPClient", FakeClient)

    tools = asyncio.run(mcp_mod.build_mcp_tools(tmp_path, disabled_servers={"only"}))
    assert tools == []
    assert called["yes"] is False


def test_mcp_discovery_stops_after_bounded_candidates(monkeypatch: pytest.MonkeyPatch) -> None:
    import langchain_mcp_adapters.sessions as sessions_mod
    from mcp.types import ListToolsResult, Tool

    import local_host.tools.mcp as mcp_mod

    pages = 0

    class FakeSession:
        async def initialize(self) -> None:
            return None

        async def list_tools(self, cursor=None):
            nonlocal pages
            pages += 1
            start = (pages - 1) * 40
            return ListToolsResult(
                tools=[
                    Tool(
                        name=f"tool_{index}",
                        description="Bounded test tool.",
                        inputSchema={"type": "object", "properties": {}},
                    )
                    for index in range(start, start + 40)
                ],
                nextCursor=f"page-{pages + 1}",
            )

    @asynccontextmanager
    async def fake_create_session(_connection):
        yield FakeSession()

    monkeypatch.setattr(sessions_mod, "create_session", fake_create_session)
    tools = asyncio.run(
        mcp_mod._build_mcp_tools_from_config(
            {"server": {"transport": "stdio", "command": "unused"}}
        )
    )

    assert pages == 2
    assert len(tools) == mcp_mod.MAX_MCP_TOOLS


def test_mcp_websocket_discovery_is_rejected(monkeypatch: pytest.MonkeyPatch) -> None:
    import langchain_mcp_adapters.sessions as sessions_mod

    import local_host.tools.mcp as mcp_mod

    @asynccontextmanager
    async def unexpected_session(_connection):
        raise AssertionError("websocket connection should not open")
        yield

    monkeypatch.setattr(sessions_mod, "create_session", unexpected_session)
    tools = asyncio.run(
        mcp_mod._build_mcp_tools_from_config(
            {"remote": {"transport": "websocket", "url": "wss://example.com/mcp"}}
        )
    )
    assert tools == []


@pytest.mark.parametrize("alias", ["http", "streamable-http"])
def test_mcp_http_aliases_receive_bounded_client(
    alias: str, monkeypatch: pytest.MonkeyPatch
) -> None:
    import langchain_mcp_adapters.sessions as sessions_mod
    from mcp.types import ListToolsResult

    import local_host.tools.mcp as mcp_mod

    captured: dict[str, object] = {}

    class FakeSession:
        async def initialize(self) -> None:
            return None

        async def list_tools(self, cursor=None):
            return ListToolsResult(tools=[])

    @asynccontextmanager
    async def fake_create_session(connection):
        captured.update(connection)
        yield FakeSession()

    monkeypatch.setattr(sessions_mod, "create_session", fake_create_session)
    asyncio.run(
        mcp_mod._build_mcp_tools_from_config(
            {"remote": {"transport": alias, "url": "https://example.com/mcp"}}
        )
    )
    assert captured["httpx_client_factory"] is mcp_mod._bounded_http_client


def test_build_agent_uses_runtime_catalog_with_disabled_servers(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """P6 reads MCP tools through the Runtime-owned catalog."""
    from langgraph.store.memory import InMemoryStore

    import local_host.agent.builder as builder_mod
    from local_host.agent.builder import build_agent, open_checkpointer
    from local_host.store.sqlite import LocalStore

    captured: dict[str, object] = {}

    async def fake_build_tools(**kwargs):
        return []

    class FakeCatalog:
        async def get_tools(self, **kwargs):
            captured.update(kwargs)
            return []

    def fake_create_deep_agent(**kwargs):
        return object()

    monkeypatch.setattr(builder_mod, "build_tools", fake_build_tools)
    monkeypatch.setattr(builder_mod, "create_deep_agent", fake_create_deep_agent)

    async def run() -> set[str] | None:
        reset_settings_for_tests(data_dir=tmp_path)
        monkeypatch.delenv("SHEJANE_LOCAL_MCP_SERVERS", raising=False)
        store = await LocalStore.open(tmp_path / "store.db")
        saver, stack = await open_checkpointer()
        try:
            await build_agent(
                store=store,
                checkpointer=saver,
                agent_store=InMemoryStore(),
                workspace_root=str(tmp_path),
                run_id="r-disabled",
                mcp_enabled=True,
                mcp_disabled_servers={"github", "playwright"},
                mcp_catalog=FakeCatalog(),
            )
            return captured.get("disabled_servers")  # type: ignore[return-value]
        finally:
            await store.close()
            await stack.aclose()

    result = asyncio.run(run())
    assert result == {"github", "playwright"}
