import { OPENROUTER_BASE_URL } from './model-options'
import type { ModelPreset } from './types'

export const MODEL_PRESETS: ModelPreset[] = [
  {
    id: 'deepseek-flash',
    label: 'DeepSeek Flash',
    helper: '¥2 / 1M',
    patch: {
      capability: 'chat',
      slot: 'deepseek-v4-flash',
      provider_kind: 'openai-compatible',
      display_name: 'DeepSeek V4 Flash',
      vendor: 'DeepSeek',
      vendor_info: '深度求索，推理能力与性价比突出。',
      capability_tier: 'fast',
      description: 'OpenRouter 高使用量编码模型,适合快速问答、代码补全和低成本任务',
      base_url: OPENROUTER_BASE_URL,
      model_name: 'deepseek/deepseek-v4-flash',
      credit_multiplier: '0.1',
      input_credit_multiplier: '0.1',
      output_credit_multiplier: '0.1',
      cache_write_credit_multiplier: '0.1',
      input_price_per_million_cny: '2',
      output_price_per_million_cny: '2',
      cache_write_price_per_million_cny: '2',
      priority: '95',
    },
  },
  {
    id: 'deepseek-pro',
    label: 'DeepSeek Pro',
    helper: '¥20 / 1M',
    patch: {
      capability: 'chat',
      slot: 'deepseek-v4-pro',
      provider_kind: 'openai-compatible',
      display_name: 'DeepSeek V4 Pro',
      vendor: 'DeepSeek',
      vendor_info: '深度求索，推理能力与性价比突出。',
      capability_tier: 'reasoning',
      description: 'DeepSeek 基准强推理模型,适合复杂分析、多步任务和代码审查',
      base_url: OPENROUTER_BASE_URL,
      model_name: 'deepseek/deepseek-v4-pro',
      credit_multiplier: '1',
      input_credit_multiplier: '1',
      output_credit_multiplier: '1',
      cache_write_credit_multiplier: '1',
      input_price_per_million_cny: '20',
      output_price_per_million_cny: '20',
      cache_write_price_per_million_cny: '20',
      priority: '90',
    },
  },
  {
    id: 'mimo-v2-5',
    label: 'Mimo V2.5',
    helper: '¥10 / ¥16',
    patch: {
      capability: 'chat',
      slot: 'mimo-v2-5',
      provider_kind: 'openai-compatible',
      display_name: 'Mimo V2.5',
      vendor: 'Xiaomi',
      vendor_info: '小米模型，适合快速问答与编码辅助。',
      capability_tier: 'balanced',
      description: 'OpenRouter 编程榜高使用量模型,适合代码生成和日常开发任务',
      base_url: OPENROUTER_BASE_URL,
      model_name: 'xiaomi/mimo-v2.5',
      credit_multiplier: '0.6',
      input_credit_multiplier: '0.5',
      output_credit_multiplier: '0.8',
      cache_write_credit_multiplier: '0.5',
      input_price_per_million_cny: '10',
      output_price_per_million_cny: '16',
      cache_write_price_per_million_cny: '10',
      priority: '88',
    },
  },
  {
    id: 'minimax-m3',
    label: 'MiniMax M3',
    helper: '¥10 / ¥30',
    patch: {
      capability: 'chat',
      slot: 'minimax-m3',
      provider_kind: 'openai-compatible',
      display_name: 'MiniMax M3',
      vendor: 'MiniMax',
      vendor_info: 'MiniMax 出品，适合长上下文和 Agent 任务。',
      capability_tier: 'reasoning',
      description: '适合长上下文、工具调用、代理式编码和多步执行',
      base_url: OPENROUTER_BASE_URL,
      model_name: 'minimax/minimax-m3',
      credit_multiplier: '1',
      input_credit_multiplier: '0.5',
      output_credit_multiplier: '1.5',
      cache_write_credit_multiplier: '0.5',
      input_price_per_million_cny: '10',
      output_price_per_million_cny: '30',
      cache_write_price_per_million_cny: '10',
      priority: '86',
    },
  },
  {
    id: 'gpt-5-5',
    label: 'GPT-5.5',
    helper: '¥80 / ¥160',
    patch: {
      capability: 'chat',
      slot: 'gpt-5-5',
      provider_kind: 'openai-compatible',
      display_name: 'GPT-5.5',
      vendor: 'ChatGPT',
      vendor_info: 'OpenAI 出品，通用能力全面。',
      capability_tier: 'max',
      description: 'OpenAI 前沿通用模型模板,适合高难度推理、写作和综合任务',
      base_url: OPENROUTER_BASE_URL,
      model_name: 'openai/gpt-5.5',
      credit_multiplier: '6',
      input_credit_multiplier: '4',
      output_credit_multiplier: '8',
      cache_write_credit_multiplier: '4',
      input_price_per_million_cny: '80',
      output_price_per_million_cny: '160',
      cache_write_price_per_million_cny: '80',
      priority: '82',
    },
  },
  {
    id: 'claude-opus',
    label: 'Claude Opus',
    helper: '¥80 / ¥160',
    patch: {
      capability: 'chat',
      slot: 'claude-opus-4-8',
      provider_kind: 'openai-compatible',
      display_name: 'Claude Opus 4.8',
      vendor: 'Claude',
      vendor_info: 'Anthropic 出品，擅长写作、代码与长文理解。',
      capability_tier: 'max',
      description: 'OpenRouter 编程榜强模型模板,适合复杂架构、长文推理和高风险改动',
      base_url: OPENROUTER_BASE_URL,
      model_name: 'anthropic/claude-opus-4.8',
      credit_multiplier: '6',
      input_credit_multiplier: '4',
      output_credit_multiplier: '8',
      cache_write_credit_multiplier: '4',
      input_price_per_million_cny: '80',
      output_price_per_million_cny: '160',
      cache_write_price_per_million_cny: '80',
      priority: '80',
    },
  },
  {
    id: 'kimi-k2',
    label: 'Kimi K2',
    helper: '¥16 / ¥40',
    patch: {
      capability: 'chat',
      slot: 'kimi-k2',
      provider_kind: 'openai-compatible',
      display_name: 'Kimi K2',
      vendor: 'Kimi',
      vendor_info: '月之暗面，擅长长上下文与长文档。',
      capability_tier: 'reasoning',
      description: 'Moonshot/Kimi 长上下文与推理模板,适合资料整理和复杂问答',
      base_url: OPENROUTER_BASE_URL,
      model_name: 'moonshotai/kimi-k2',
      credit_multiplier: '1.2',
      input_credit_multiplier: '0.8',
      output_credit_multiplier: '2',
      cache_write_credit_multiplier: '0.8',
      input_price_per_million_cny: '16',
      output_price_per_million_cny: '40',
      cache_write_price_per_million_cny: '16',
      priority: '76',
    },
  },
  {
    id: 'openai-compatible',
    label: 'OpenAI 兼容',
    helper: '空白模板',
    patch: {
      capability: 'chat',
      provider_kind: 'openai-compatible',
      vendor: 'ChatGPT',
      vendor_info: 'OpenAI 出品，通用能力全面。',
      capability_tier: 'balanced',
      base_url: OPENROUTER_BASE_URL,
      model_name: '',
    },
  },
]
