import type { ToolDefinition } from '../types.js'

export const localHostTools: ToolDefinition[] = [
  {
    name: 'time.now',
    description: 'Return the current local time and timezone for the user session.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 4096,
    permissionPolicy: 'allow',
  },
  {
    name: 'workspace.open',
    description: 'Open or register a user-approved workspace path for a run.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path'],
      properties: {
        path: { type: 'string' },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'file.read',
    description: 'Legacy alias for fs.read. Read a file inside an already authorized workspace.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path'],
      properties: {
        path: { type: 'string' },
        maxBytes: { type: 'number', minimum: 1, maximum: 65536 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'file.search',
    description: 'Legacy alias for fs.search. Search filenames or file text inside an already authorized workspace.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['query'],
      properties: {
        query: { type: 'string' },
        path: { type: 'string' },
        maxResults: { type: 'number', minimum: 1, maximum: 100 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'file.write',
    description: 'Legacy alias for fs.write. Create or overwrite a UTF-8 text file inside an authorized workspace after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path', 'content'],
      properties: {
        path: { type: 'string' },
        content: { type: 'string' },
        createDirs: { type: 'boolean' },
      },
    },
    isReadOnly: false,
    isDestructive: true,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'fs.list',
    description: 'List files and folders inside an authorized workspace directory.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        path: { type: 'string' },
        maxEntries: { type: 'number', minimum: 1, maximum: 500 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'fs.read',
    description: 'Read a file inside an already authorized workspace.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path'],
      properties: {
        path: { type: 'string' },
        maxBytes: { type: 'number', minimum: 1, maximum: 65536 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'fs.search',
    description: 'Search filenames or file text inside an already authorized workspace.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['query'],
      properties: {
        query: { type: 'string' },
        path: { type: 'string' },
        maxResults: { type: 'number', minimum: 1, maximum: 100 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'fs.write',
    description: 'Create or overwrite a UTF-8 text file inside an authorized workspace after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path', 'content'],
      properties: {
        path: { type: 'string' },
        content: { type: 'string' },
        createDirs: { type: 'boolean' },
      },
    },
    isReadOnly: false,
    isDestructive: true,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'open.url',
    description: 'Open a public http(s) URL in the system default browser after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['url'],
      properties: {
        url: { type: 'string' },
      },
    },
    isReadOnly: false,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'open.file',
    description: 'Open a file inside an authorized workspace with the system default app after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path'],
      properties: {
        path: { type: 'string' },
      },
    },
    isReadOnly: false,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'clipboard.read',
    description: 'Read plain text from the system clipboard after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'ask',
  },
  {
    name: 'clipboard.write',
    description: 'Write plain text to the system clipboard after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['text'],
      properties: {
        text: { type: 'string' },
      },
    },
    isReadOnly: false,
    isDestructive: true,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'task.verify',
    description: 'Verify a simple task condition such as file existence, file content, URL shape, or boolean assertion.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['check'],
      properties: {
        check: { type: 'string', enum: ['file_exists', 'file_contains', 'url_valid', 'boolean'] },
        path: { type: 'string' },
        text: { type: 'string' },
        url: { type: 'string' },
        value: { type: 'boolean' },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 4096,
    permissionPolicy: 'allow',
  },
  {
    name: 'shell.run',
    description: 'Run a shell command in an authorized workspace after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['command'],
      properties: {
        command: { type: 'string' },
        cwd: { type: 'string' },
        timeoutMs: { type: 'number', minimum: 1000, maximum: 120000 },
      },
    },
    isReadOnly: false,
    isDestructive: true,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'ask',
  },
  {
    name: 'web.fetch',
    description: 'Fetch a public HTTP(S) URL with SSRF protection, timeout, text extraction, and source metadata.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['url'],
      properties: {
        url: { type: 'string' },
        maxBytes: { type: 'number', minimum: 1024, maximum: 262144 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'web.search',
    description: 'Search the public web through the configured local search provider. Tavily is supported in this MVP.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['query'],
      properties: {
        query: { type: 'string' },
        maxResults: { type: 'number', minimum: 1, maximum: 10 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'mcp.call',
    description: 'Call an allowlisted local MCP tool through the configured local stdio MCP runtime adapter.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['server', 'tool', 'input'],
      properties: {
        server: { type: 'string' },
        tool: { type: 'string' },
        input: { type: 'object' },
      },
    },
    isReadOnly: false,
    isDestructive: true,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'ask',
  },
]
