import type { ToolDefinition } from '../types.js'

export const localHostTools: ToolDefinition[] = [
  {
    name: 'time.now',
    description: 'Return the current local time and timezone for the user session.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 4096,
    permissionPolicy: 'allow',
  },
  {
    name: 'workspace.open',
    description: 'Open or register a user-approved workspace path for a run.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path'],
      properties: {
        path: { type: 'string' },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'file.read',
    description: 'Read a file inside an already authorized workspace.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path'],
      properties: {
        path: { type: 'string' },
        maxBytes: { type: 'number', minimum: 1, maximum: 65536 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'file.search',
    description: 'Search filenames or file text inside an already authorized workspace.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['query'],
      properties: {
        query: { type: 'string' },
        path: { type: 'string' },
        maxResults: { type: 'number', minimum: 1, maximum: 100 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'shell.run',
    description: 'Run a shell command in an authorized workspace after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['command'],
      properties: {
        command: { type: 'string' },
        cwd: { type: 'string' },
        timeoutMs: { type: 'number', minimum: 1000, maximum: 120000 },
      },
    },
    isReadOnly: false,
    isDestructive: true,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'ask',
  },
  {
    name: 'web.fetch',
    description: 'Fetch a public HTTP(S) URL with SSRF protection, timeout, text extraction, and source metadata.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['url'],
      properties: {
        url: { type: 'string' },
        maxBytes: { type: 'number', minimum: 1024, maximum: 262144 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'web.search',
    description: 'Search the public web through the configured local search provider. Tavily is supported in this MVP.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['query'],
      properties: {
        query: { type: 'string' },
        maxResults: { type: 'number', minimum: 1, maximum: 10 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'mcp.call',
    description: 'Call an allowlisted local MCP tool through the configured local stdio MCP runtime adapter.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['server', 'tool', 'input'],
      properties: {
        server: { type: 'string' },
        tool: { type: 'string' },
        input: { type: 'object' },
      },
    },
    isReadOnly: false,
    isDestructive: true,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'ask',
  },
]
