import type { ToolDefinition } from '../types.js'

export const localHostTools: ToolDefinition[] = [
  {
    name: 'time.now',
    description: 'Return the current local time and timezone for the user session.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 4096,
    permissionPolicy: 'allow',
  },
  {
    name: 'workspace.open',
    description: 'Open or register a user-approved workspace path for a run.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path'],
      properties: {
        path: { type: 'string' },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'file.read',
    description: 'Legacy alias for fs.read. Read a file inside an already authorized workspace.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path'],
      properties: {
        path: { type: 'string' },
        maxBytes: { type: 'number', minimum: 1, maximum: 65536 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'file.search',
    description: 'Legacy alias for fs.search. Search filenames or file text inside an already authorized workspace.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['query'],
      properties: {
        query: { type: 'string' },
        path: { type: 'string' },
        maxResults: { type: 'number', minimum: 1, maximum: 100 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'file.write',
    description: 'Legacy alias for fs.write. Create or overwrite a UTF-8 text file inside an authorized workspace after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path', 'content'],
      properties: {
        path: { type: 'string' },
        content: { type: 'string' },
        createDirs: { type: 'boolean' },
      },
    },
    isReadOnly: false,
    isDestructive: true,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'fs.list',
    description: 'List files and folders inside an authorized workspace directory.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        path: { type: 'string' },
        maxEntries: { type: 'number', minimum: 1, maximum: 500 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'fs.read',
    description: 'Read a file inside an already authorized workspace.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path'],
      properties: {
        path: { type: 'string' },
        maxBytes: { type: 'number', minimum: 1, maximum: 65536 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'fs.search',
    description: 'Search filenames or file text inside an already authorized workspace.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['query'],
      properties: {
        query: { type: 'string' },
        path: { type: 'string' },
        maxResults: { type: 'number', minimum: 1, maximum: 100 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'fs.write',
    description: 'Create or overwrite a UTF-8 text file inside an authorized workspace after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path', 'content'],
      properties: {
        path: { type: 'string' },
        content: { type: 'string' },
        createDirs: { type: 'boolean' },
      },
    },
    isReadOnly: false,
    isDestructive: true,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'open.url',
    description: 'Open a public http(s) URL in the system default browser after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['url'],
      properties: {
        url: { type: 'string' },
      },
    },
    isReadOnly: false,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'open.file',
    description: 'Open a file inside an authorized workspace with the system default app after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['path'],
      properties: {
        path: { type: 'string' },
      },
    },
    isReadOnly: false,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'clipboard.read',
    description: 'Read plain text from the system clipboard after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'ask',
  },
  {
    name: 'clipboard.write',
    description: 'Write plain text to the system clipboard after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['text'],
      properties: {
        text: { type: 'string' },
      },
    },
    isReadOnly: false,
    isDestructive: true,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'task.verify',
    description: 'Verify a simple task condition such as file existence, file content, URL shape, or boolean assertion.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['check'],
      properties: {
        check: { type: 'string', enum: ['file_exists', 'file_contains', 'url_valid', 'boolean'] },
        path: { type: 'string' },
        text: { type: 'string' },
        url: { type: 'string' },
        value: { type: 'boolean' },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 4096,
    permissionPolicy: 'allow',
  },
  {
    name: 'browser.open',
    description: 'Open a public http(s) URL in the Playwright-managed browser after explicit user approval, then capture a structured page snapshot.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['url'],
      properties: {
        url: { type: 'string' },
        maxTextCharacters: { type: 'number', minimum: 1, maximum: 60000 },
      },
    },
    isReadOnly: false,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'ask',
  },
  {
    name: 'browser.search',
    description: 'Search the public web in the Playwright-managed browser after explicit user approval, then capture a structured results-page snapshot.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['query'],
      properties: {
        query: { type: 'string' },
        maxTextCharacters: { type: 'number', minimum: 1, maximum: 60000 },
      },
    },
    isReadOnly: false,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'ask',
  },
  {
    name: 'browser.snapshot',
    description: 'Read the current Playwright-managed browser page title, URL, visible text, links, forms, buttons, and interactive element refs.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        maxTextCharacters: { type: 'number', minimum: 1, maximum: 60000 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'browser.read',
    description: 'Read the current Playwright-managed browser page main text, title, URL, meta description, and key links. Use after opening a source page to collect evidence.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        maxTextCharacters: { type: 'number', minimum: 1, maximum: 60000 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'browser.verify',
    description: 'Verify the current managed browser page against expected visible text or page usability, optionally capturing a screenshot artifact for evidence.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        expectText: { type: 'string' },
        requireUsable: { type: 'boolean' },
        includeScreenshot: { type: 'boolean' },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'browser.screenshot',
    description: 'Capture a PNG screenshot of the current managed browser page and store it as a local artifact.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        fullPage: { type: 'boolean' },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'allow',
  },
  {
    name: 'browser.click',
    description: 'Click an interactive element by snapshot ref in the managed browser after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['ref'],
      properties: {
        ref: { type: 'string' },
        maxTextCharacters: { type: 'number', minimum: 1, maximum: 60000 },
      },
    },
    isReadOnly: false,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'ask',
  },
  {
    name: 'browser.type',
    description: 'Type plain text into an interactive element by snapshot ref in the managed browser after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['ref', 'text'],
      properties: {
        ref: { type: 'string' },
        text: { type: 'string' },
        maxTextCharacters: { type: 'number', minimum: 1, maximum: 60000 },
      },
    },
    isReadOnly: false,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'ask',
  },
  {
    name: 'browser.scroll',
    description: 'Scroll the current managed browser page and return an updated structured snapshot.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {
        direction: { type: 'string', enum: ['up', 'down'] },
        amount: { type: 'number', minimum: 100, maximum: 5000 },
        maxTextCharacters: { type: 'number', minimum: 1, maximum: 60000 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'browser.close',
    description: 'Close the current Playwright-managed browser page context.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    isReadOnly: false,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'allow',
  },
  {
    name: 'environment.observe',
    description: 'Observe basic local environment information such as platform and foreground window metadata after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      properties: {},
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: false,
    maxResultSize: 4096,
    permissionPolicy: 'ask',
  },
  {
    name: 'shell.run',
    description: 'Run a shell command in an authorized workspace after explicit user approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['command'],
      properties: {
        command: { type: 'string' },
        cwd: { type: 'string' },
        timeoutMs: { type: 'number', minimum: 1000, maximum: 120000 },
      },
    },
    isReadOnly: false,
    isDestructive: true,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'ask',
  },
  {
    name: 'web.fetch',
    description: 'Fetch a public HTTP(S) URL with SSRF protection, timeout, text extraction, and source metadata.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['url'],
      properties: {
        url: { type: 'string' },
        maxBytes: { type: 'number', minimum: 1024, maximum: 262144 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'web.search',
    description: 'Search the public web through the configured local search provider. Tavily is supported in this MVP.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['query'],
      properties: {
        query: { type: 'string' },
        maxResults: { type: 'number', minimum: 1, maximum: 10 },
      },
    },
    isReadOnly: true,
    isDestructive: false,
    isConcurrencySafe: true,
    maxResultSize: 65536,
    permissionPolicy: 'allow',
  },
  {
    name: 'mcp.call',
    description: 'Call an allowlisted local MCP tool through the configured local stdio MCP runtime adapter.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['server', 'tool', 'input'],
      properties: {
        server: { type: 'string' },
        tool: { type: 'string' },
        input: { type: 'object' },
      },
    },
    isReadOnly: false,
    isDestructive: true,
    isConcurrencySafe: false,
    maxResultSize: 65536,
    permissionPolicy: 'ask',
  },
]
