/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/local/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description Return a single artifact record.
         *
         *     Shape matches the TS `LocalArtifact` interface
         *     (`client.ts:38-44`): `{id, title, content, tool_name?, created_at?}`.
         */
        get: operations["get_artifact_local_v1_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_local_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/mcp-servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Mcp Servers
         * @description Catalog of every MCP server we discovered across the user's
         *     machine. Pure read — we never start, install, or modify these
         *     servers. The user manages them through whatever tool they
         *     prefer (Claude Desktop, Cursor, Codex, or our own
         *     `~/.shejane/mcp-servers.json`), and the daemon picks them up
         *     on the next agent boot.
         *
         *     `sources_scanned` reports the source labels we attempted to
         *     read (regardless of whether the file existed or had servers),
         *     so the UI can render section headers like "Cursor — no
         *     config found at ~/.cursor/mcp.json" instead of silently
         *     hiding the section.
         */
        get: operations["list_mcp_servers_local_v1_mcp_servers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear Memory
         * @description Wipe every note from all long-term memory namespaces.
         *
         *     Backs the "清空记忆 / Clear memory" button in the agent settings
         *     dialog. Walks every ("notes", ...) namespace in pages of 200
         *     (matches the BaseStore default search limit ceiling for SQLite stores)
         *     and deletes each key. Returns the total count so the UI can render an
         *     accurate "cleared N memories" toast.
         *
         *     Idempotent: calling it on an empty store returns
         *     `deleted_count: 0` without error.
         */
        delete: operations["clear_memory_local_v1_memory_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/permissions/{permission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Permission
         * @description Approve / deny a pending tool-permission request.
         *
         *     Translates the client's `{decision, scope}` body into the
         *     `{"decisions": [{"type": "approve"|"reject", ...}]}` shape
         *     that `HumanInTheLoopMiddleware` expects on resume (the
         *     middleware does `interrupt(...)["decisions"]` and KeyError's
         *     on anything else).
         *
         *     When `scope=run`, the coordinator caches the tool name so the
         *     auto-approve loop in `_drive_run` skips re-prompting on
         *     subsequent gates for the same tool in the same run.
         */
        post: operations["resolve_permission_local_v1_permissions__permission_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/pptx-outline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pptx Outline
         * @description Return the slide outline JSON for a .pptx file.
         *
         *     Used by the right-side DocPreviewPanel's PptxPreview component
         *     — pptx has no mature pure-browser renderer, so the panel renders
         *     a structured outline (title + bullets + notes per slide) here
         *     rather than embedding a viewer in iframe.
         *
         *     Gated by `local_workspaces`, same as `/workspace-files`. The
         *     path's parent chain must be inside a previously-authorized
         *     workspace. Calls the shared `_outline_pptx` helper that
         *     `office.outline` and `office.read_slides` also use, so the
         *     JSON shape is identical to those tools.
         */
        get: operations["get_pptx_outline_local_v1_pptx_outline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer Question
         * @description Submit answers to a paused user.ask interrupt.
         *
         *     Body shape (per `client.ts:answerLocalQuestion`):
         *     `{answers: Record<string, string[]>}`. We look up the question
         *     by id to find its run_id, persist the answers, then resume.
         */
        post: operations["answer_question_local_v1_questions__question_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Recent runs newest-first.
         *
         *     Client `listLocalRuns()` (client/src/shared/local-host/client.ts:283)
         *     reads `{runs: LocalRun[]}` on every boot. Previously this route
         *     didn't exist — every Electron launch silently 404'd here and
         *     the conversation history sidebar came up empty.
         */
        get: operations["list_runs_local_v1_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Create a new run. Returns the flat `LocalRun` shape (NOT
         *     `{run: {...}}`) — that's the contract `client.test.ts:63-92`
         *     pins and what TypeScript's `createLocalRun` reads via
         *     `decodeLocalResponse<LocalRun>`.
         */
        post: operations["create_run_local_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Return the flat run record (same shape as POST /runs).
         */
        get: operations["get_run_local_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_local_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/runs/{run_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Diagnostics
         * @description Return the full `LocalRunDiagnostics` payload.
         *
         *     Shape (per TS interface `client/src/shared/local-host/client.ts`):
         *         { schema_version: 1, exported_at, local_host_version?,
         *           run, events, permissions, artifacts, latest_checkpoint, handoff }
         *
         *     Phase 5'+ used to return only `{run, events}`, so the
         *     `DiagnosticsPanel` rendered NaN counts (permissions.length on
         *     undefined) and the "latest checkpoint" tab was always missing.
         */
        get: operations["run_diagnostics_local_v1_runs__run_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_local_v1_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run */
        get: operations["stream_run_local_v1_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cloud Session */
        get: operations["get_cloud_session_local_v1_session_get"];
        put?: never;
        /**
         * Set Cloud Session
         * @description Stash a cloud bearer token (+ base URL) for outbound LLM calls.
         *
         *     Response shape MUST match the client's `LocalCloudSession` TypeScript
         *     interface — the client gates its "use local agent" feature flag on
         *     `session.connected === true`. The pydantic model + response_model
         *     now enforce that.
         */
        post: operations["set_cloud_session_local_v1_session_post"];
        /** Clear Cloud Session */
        delete: operations["clear_cloud_session_local_v1_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Local Skills
         * @description Catalog of every SKILL.md the daemon can see across all
         *     configured skill roots (`~/.shejane/skills/`, `~/.claude/skills/`,
         *     or `SHEJANE_LOCAL_SKILLS_PATH` overrides). Skills are managed
         *     out-of-band — the user drops directories into a root themselves
         *     (or installs via the skills.sh CLI into `~/.claude/skills/`) and
         *     the daemon picks them up on next scan.
         *
         *     Also surfaces the roots themselves under `roots` so the UI can
         *     render section headers (e.g. "Personal" for shejane) even when
         *     a root is empty — otherwise the user has no idea where to drop
         *     their SKILL.md directories.
         */
        get: operations["list_local_skills_local_v1_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tools */
        get: operations["list_tools_local_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/workspace-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workspace File
         * @description Stream a file's bytes back to the renderer.
         *
         *     Gated by `local_workspaces` — the file's parent chain must be inside
         *     a path the user previously authorized via `workspace.open`. We do
         *     NOT serve arbitrary paths; that would let a compromised renderer
         *     exfiltrate the entire disk.
         *
         *     Used by the right-side DocPreviewPanel to fetch .docx / .xlsx
         *     bytes for in-browser rendering (docx-preview, exceljs). No
         *     response_model — this is a binary stream, not a JSON shape, so
         *     it stays out of api_schemas.py / openapi.json by design.
         */
        get: operations["get_workspace_file_local_v1_workspace_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_local_v1_workspaces_get"];
        put?: never;
        /**
         * Add Workspace
         * @description Authorize a workspace path. Returns the flat row — the TS
         *     `authorizeLocalWorkspace` reads `.id / .path / .label` directly
         *     (no wrapper).
         */
        post: operations["add_workspace_local_v1_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/workspaces/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diagnose Workspace
         * @description Inspect a candidate path against the authorization registry.
         *
         *     Response matches the TS `LocalWorkspaceDiagnosis` shape — the
         *     `reason` enum drives the workspace-picker's "why disabled?"
         *     copy, keep it stable.
         */
        post: operations["diagnose_workspace_local_v1_workspaces_diagnose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Workspace
         * @description Revoke a workspace authorization. Returns the deleted row
         *     matching the TS `revokeLocalWorkspace` →
         *     `Promise<LocalWorkspaceAuthorization>` signature.
         */
        delete: operations["remove_workspace_local_v1_workspaces__workspace_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerQuestionRequest */
        AnswerQuestionRequest: {
            /** Answers */
            answers: {
                [key: string]: string[];
            };
        };
        /** CancelRunResponse */
        CancelRunResponse: {
            /** Canceled */
            canceled: boolean;
        };
        /**
         * ClearMemoryResponse
         * @description DELETE /local/v1/memory — wipes the agent's long-term notes.
         *
         *     Reported back so the renderer can show "cleared N memories" toast
         *     instead of a generic "done" message.
         */
        ClearMemoryResponse: {
            /**
             * Cleared
             * @default true
             * @constant
             */
            cleared: true;
            /** Deleted Count */
            deleted_count: number;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Goal */
            goal: string;
            /** History */
            history?: {
                [key: string]: string;
            }[] | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Model
             * @default auto
             */
            model: string;
            /** Parent Run Id */
            parent_run_id?: string | null;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
            /** Workspace Path */
            workspace_path?: string | null;
        };
        /** CreateWorkspaceRequest */
        CreateWorkspaceRequest: {
            /**
             * Label
             * @default
             */
            label: string;
            /** Path */
            path: string;
        };
        /** DiagnoseWorkspaceRequest */
        DiagnoseWorkspaceRequest: {
            /** Path */
            path: string;
        };
        /** DiagnosticsArtifact */
        DiagnosticsArtifact: {
            /** Bytes */
            bytes: number;
            /** Content Type */
            content_type: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            /** Title */
            title: string;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Tool Name */
            tool_name?: string | null;
        };
        /**
         * DiagnosticsEvent
         * @description One row from the `local_events` table after payload parsing.
         *
         *     Matches the AgentRunEvent envelope the client's
         *     `parseAgentSSEChunk` produces (intentional, so the diagnostics
         *     panel can reuse the live-stream renderer).
         */
        DiagnosticsEvent: {
            /** Created At */
            created_at: string;
            /** Event Type */
            event_type: string;
            /** Id */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
        };
        /**
         * DiagnosticsFailure
         * @description Structured classification for the latest failed run/tool event.
         */
        DiagnosticsFailure: {
            /**
             * Action Kind
             * @enum {string}
             */
            action_kind: "retry" | "user_action" | "repair" | "operator_action" | "inspect";
            /**
             * Category
             * @enum {string}
             */
            category: "transient" | "auth" | "quota" | "permission" | "configuration" | "workspace" | "validation" | "fatal" | "unknown";
            /** Code */
            code?: string | null;
            /** Message */
            message: string;
            /** Recoverable */
            recoverable: boolean;
            /** Retryable */
            retryable: boolean;
            /** Source Event Type */
            source_event_type: string;
            /** Suggested Action */
            suggested_action: string;
            /** Tool */
            tool?: string | null;
        };
        /**
         * DiagnosticsHandoff
         * @description Compact handoff summary for long-running or resumed work.
         *
         *     This is derived from redacted run metadata and event types. It deliberately
         *     does not include full checkpoint messages, artifact bodies, or raw tool
         *     output.
         */
        DiagnosticsHandoff: {
            /** Blockers */
            blockers?: string[];
            failure?: components["schemas"]["DiagnosticsFailure"] | null;
            /** Headline */
            headline: string;
            /** Ledger Message */
            ledger_message?: string | null;
            /**
             * Ledger State
             * @default not_required
             * @enum {string}
             */
            ledger_state: "not_required" | "missing" | "fresh" | "stale";
            /** Next Actions */
            next_actions?: string[];
            /** Recent Event Types */
            recent_event_types?: string[];
            /** Status */
            status: string;
            verification?: components["schemas"]["DiagnosticsVerification"] | null;
        };
        /** DiagnosticsPermission */
        DiagnosticsPermission: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Resolved At */
            resolved_at?: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Scope
             * @default once
             * @enum {string}
             */
            scope: "once" | "run";
            /** Status */
            status: string;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Tool Name */
            tool_name: string;
        };
        /**
         * DiagnosticsReflection
         * @description Safe reflection summary from the latest checkpoint.
         *
         *     This deliberately excludes checkpoint messages and raw tool output.
         */
        DiagnosticsReflection: {
            /** Ai Messages */
            ai_messages?: number | null;
            critic?: components["schemas"]["DiagnosticsReflectionCritic"] | null;
            /** Final Answer Chars */
            final_answer_chars?: number | null;
            /** Tool Results */
            tool_results?: number | null;
        };
        /**
         * DiagnosticsReflectionCritic
         * @description Compact final-answer critic output, if reflection ran.
         */
        DiagnosticsReflectionCritic: {
            /** Clarity */
            clarity?: number | null;
            /** Coverage */
            coverage?: number | null;
            /** Grounding */
            grounding?: number | null;
            /** Notes */
            notes?: string[];
            /** Raw */
            raw?: string | null;
        };
        /**
         * DiagnosticsVerification
         * @description Latest machine-readable task.verify result, if any.
         */
        DiagnosticsVerification: {
            /** Fail Count */
            fail_count?: number | null;
            /** Pass Count */
            pass_count?: number | null;
            /** Reason */
            reason?: string | null;
            /** Source Event Type */
            source_event_type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "passed" | "failed";
        };
        /**
         * FeatureLedger
         * @description Latest durable progress ledger entry for the run.
         */
        FeatureLedger: {
            /** Acceptance Criteria */
            acceptance_criteria?: string[];
            /** Artifact Id */
            artifact_id?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Decisions */
            decisions?: string[];
            /** Files Touched */
            files_touched?: string[];
            /** Next Actions */
            next_actions?: string[];
            /** Status */
            status: string;
            /** Summary */
            summary: string;
            /** Unresolved Risks */
            unresolved_risks?: string[];
            /** Validation Commands */
            validation_commands?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description GET /local/v1/health — no auth required.
         *
         *     Both `ok` (legacy smoke contract) and `status` (current TS client
         *     probe) are returned. Drop `ok` once smoke scripts are updated.
         */
        HealthResponse: {
            /**
             * Mode
             * @default ready
             */
            mode: string;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Pairing Configured */
            pairing_configured: boolean;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /**
             * Worker
             * @default python-langgraph
             */
            worker: string;
        };
        /**
         * LatestCheckpoint
         * @description Slim summary of the agent run's last persisted superstep — used
         *     by the diagnostics panel to render the "where the run is paused"
         *     headline. The full LangGraph checkpoint is much larger; we just
         *     expose the fields the UI reads (`id`, `reason`, `messages_count`).
         */
        LatestCheckpoint: {
            /** Created At */
            created_at?: string | null;
            /** Id */
            id: string;
            /** Messages Count */
            messages_count: number;
            /** Reason */
            reason: string;
            /** Run Id */
            run_id?: string | null;
            /** Step */
            step: number;
        };
        /** ListRunsResponse */
        ListRunsResponse: {
            /** Runs */
            runs: components["schemas"]["LocalRun"][];
        };
        /** ListWorkspacesResponse */
        ListWorkspacesResponse: {
            /** Workspaces */
            workspaces: components["schemas"]["LocalWorkspaceAuthorization"][];
        };
        /**
         * LocalArtifact
         * @description Slim representation for `GET /artifacts/:id` (UI quoting).
         *
         *     The full row in `local_artifacts` (run_id, kind, content_type,
         *     bytes, metadata_json) is intentionally NOT returned here — that
         *     payload is for the diagnostics panel, not the chat surface.
         */
        LocalArtifact: {
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Tool Name */
            tool_name?: string | null;
        };
        /**
         * LocalCloudSession
         * @description Pairing state between the daemon and the cloud API.
         *
         *     `connected: false` is the only field on an unpaired response; the
         *     rest become present once the user logs in via the Electron app
         *     and the renderer POSTs the JWT to /local/v1/session.
         */
        LocalCloudSession: {
            /** Auth */
            auth?: "bearer" | null;
            /** Cloud Base Url */
            cloud_base_url?: string | null;
            /** Connected */
            connected: boolean;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * LocalRun
         * @description One row of the `local_runs` table, surfaced over HTTP.
         *
         *     `history_json` / `settings_json` are stringified JSON because
         *     SQLite stores them that way — the client parses on demand. Kept
         *     as strings here (not dict) to keep the wire format honest.
         */
        LocalRun: {
            /** Canceled At */
            canceled_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Created At */
            created_at: string;
            /** Events Count */
            events_count?: number | null;
            /** Goal */
            goal: string;
            /**
             * History Json
             * @default []
             */
            history_json: string;
            /** Id */
            id: string;
            /**
             * Metadata Json
             * @default {}
             */
            metadata_json: string;
            /** Parent Run Id */
            parent_run_id?: string | null;
            /**
             * Settings Json
             * @default {}
             */
            settings_json: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "waiting_permission" | "waiting_input" | "completed" | "canceled" | "failed";
            /** Updated At */
            updated_at: string;
            /** Workspace Path */
            workspace_path?: string | null;
        };
        /** LocalRunDiagnostics */
        LocalRunDiagnostics: {
            /** Artifacts */
            artifacts: components["schemas"]["DiagnosticsArtifact"][];
            /** Events */
            events: components["schemas"]["DiagnosticsEvent"][];
            /** Exported At */
            exported_at: string;
            feature_ledger?: components["schemas"]["FeatureLedger"] | null;
            handoff: components["schemas"]["DiagnosticsHandoff"];
            latest_checkpoint?: components["schemas"]["LatestCheckpoint"] | null;
            /** Local Host Version */
            local_host_version?: string | null;
            /** Permissions */
            permissions: components["schemas"]["DiagnosticsPermission"][];
            reflection?: components["schemas"]["DiagnosticsReflection"] | null;
            run: components["schemas"]["LocalRun"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** LocalWorkspaceAuthorization */
        LocalWorkspaceAuthorization: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Last Used At */
            last_used_at: string;
            /** Path */
            path: string;
        };
        /**
         * LocalWorkspaceDiagnosis
         * @description Result of POST /local/v1/workspaces/diagnose. The `reason` field
         *     drives the workspace-picker UI's "why is this disabled?" copy —
         *     keep the enum stable.
         */
        LocalWorkspaceDiagnosis: {
            /** Authorized */
            authorized: boolean;
            /** Exists */
            exists: boolean;
            /** Is Directory */
            is_directory: boolean;
            /** Path */
            path: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "authorized" | "not_authorized" | "not_found" | "not_directory";
            workspace?: components["schemas"]["LocalWorkspaceAuthorization"] | null;
        };
        /**
         * McpServerCatalog
         * @description GET /local/v1/mcp-servers — the full list of discovered servers
         *     plus the set of sources we scanned. `sources` lets the UI render
         *     empty-state hints like "no Claude Desktop config found" even when
         *     no server came from there.
         */
        McpServerCatalog: {
            /** Servers */
            servers: components["schemas"]["McpServerInfo"][];
            /** Sources Scanned */
            sources_scanned: string[];
        };
        /**
         * McpServerInfo
         * @description One MCP server we discovered on the user's machine.
         *
         *     `name` is the unique key the user (or installer tool) gave it.
         *     `transport` is the normalized transport — `stdio` / `streamable_http`
         *     / `sse` / `websocket`. `command` / `args` / `url` / `env_keys` are
         *     descriptive only — we never echo env *values* (could be secrets).
         *     `source` is one of `shejane` / `claude-desktop` / `cursor` / `codex`
         *     / `env` — used by the UI to group servers by provenance.
         *     `source_path` is the absolute path of the config file the entry was
         *     read from, displayed in the settings panel so the user knows where
         *     to go edit it.
         */
        McpServerInfo: {
            /**
             * Args
             * @default []
             */
            args: string[];
            /** Command */
            command?: string | null;
            /** Cwd */
            cwd?: string | null;
            /**
             * Env Keys
             * @default []
             */
            env_keys: string[];
            /** Name */
            name: string;
            /** Source */
            source: string;
            /** Source Path */
            source_path: string;
            /** Transport */
            transport: string;
            /** Url */
            url?: string | null;
        };
        /** PermissionResolution */
        PermissionResolution: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "deny";
            /** Permission Id */
            permission_id: string;
            /**
             * Resolved
             * @default true
             * @constant
             */
            resolved: true;
            /** Resumed */
            resumed: boolean;
            /**
             * Scope
             * @enum {string}
             */
            scope: "once" | "run";
        };
        /** QuestionAnswer */
        QuestionAnswer: {
            /**
             * Answered
             * @default true
             * @constant
             */
            answered: true;
            /** Question Id */
            question_id: string;
            /** Resumed */
            resumed: boolean;
        };
        /** ResolvePermissionRequest */
        ResolvePermissionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "deny";
            /**
             * Scope
             * @default once
             * @enum {string}
             */
            scope: "once" | "run";
        };
        /** ResumeRunResponse */
        ResumeRunResponse: {
            /**
             * Resumed
             * @default true
             * @constant
             */
            resumed: true;
        };
        /** SetCloudSessionRequest */
        SetCloudSessionRequest: {
            /** Access Token */
            access_token: string;
            /** Cloud Base Url */
            cloud_base_url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_artifact_local_v1_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalArtifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_local_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_mcp_servers_local_v1_mcp_servers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerCatalog"];
                };
            };
        };
    };
    clear_memory_local_v1_memory_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearMemoryResponse"];
                };
            };
        };
    };
    resolve_permission_local_v1_permissions__permission_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                permission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolvePermissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResolution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pptx_outline_local_v1_pptx_outline_get: {
        parameters: {
            query: {
                /** @description Absolute .pptx path inside an authorized workspace */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_question_local_v1_questions__question_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionAnswer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_local_v1_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRunsResponse"];
                };
            };
        };
    };
    create_run_local_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_local_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_local_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_diagnostics_local_v1_runs__run_id__diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalRunDiagnostics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_local_v1_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_local_v1_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cloud_session_local_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalCloudSession"];
                };
            };
        };
    };
    set_cloud_session_local_v1_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCloudSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalCloudSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cloud_session_local_v1_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalCloudSession"];
                };
            };
        };
    };
    list_local_skills_local_v1_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_tools_local_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_workspace_file_local_v1_workspace_files_get: {
        parameters: {
            query: {
                /** @description Absolute file path inside an authorized workspace */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspaces_local_v1_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWorkspacesResponse"];
                };
            };
        };
    };
    add_workspace_local_v1_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalWorkspaceAuthorization"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnose_workspace_local_v1_workspaces_diagnose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnoseWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalWorkspaceDiagnosis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_workspace_local_v1_workspaces__workspace_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalWorkspaceAuthorization"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
