/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/local/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact
         * @description Return a single artifact record.
         *
         *     Shape matches the TS `LocalArtifact` interface
         *     (`client.ts:38-44`): `{id, title, content, tool_name?, created_at?}`.
         */
        get: operations["get_artifact_local_v1_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_local_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/permissions/{permission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Permission
         * @description Approve / deny a pending tool-permission request.
         *
         *     Translates the client's `{decision, scope}` body into the
         *     `{"decisions": [{"type": "approve"|"reject", ...}]}` shape
         *     that `HumanInTheLoopMiddleware` expects on resume (the
         *     middleware does `interrupt(...)["decisions"]` and KeyError's
         *     on anything else).
         *
         *     When `scope=run`, the coordinator caches the tool name so the
         *     auto-approve loop in `_drive_run` skips re-prompting on
         *     subsequent gates for the same tool in the same run.
         */
        post: operations["resolve_permission_local_v1_permissions__permission_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer Question
         * @description Submit answers to a paused user.ask interrupt.
         *
         *     Body shape (per `client.ts:answerLocalQuestion`):
         *     `{answers: Record<string, string[]>}`. We look up the question
         *     by id to find its run_id, persist the answers, then resume.
         */
        post: operations["answer_question_local_v1_questions__question_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Recent runs newest-first.
         *
         *     Client `listLocalRuns()` (client/src/shared/local-host/client.ts:283)
         *     reads `{runs: LocalRun[]}` on every boot. Previously this route
         *     didn't exist — every Electron launch silently 404'd here and
         *     the conversation history sidebar came up empty.
         */
        get: operations["list_runs_local_v1_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Create a new run. Returns the flat `LocalRun` shape (NOT
         *     `{run: {...}}`) — that's the contract `client.test.ts:63-92`
         *     pins and what TypeScript's `createLocalRun` reads via
         *     `decodeLocalResponse<LocalRun>`.
         */
        post: operations["create_run_local_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Return the flat run record (same shape as POST /runs).
         */
        get: operations["get_run_local_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_local_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/runs/{run_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Diagnostics
         * @description Return the full `LocalRunDiagnostics` payload.
         *
         *     Shape (per TS interface `client/src/shared/local-host/client.ts:63-100`):
         *         { schema_version: 1, exported_at, local_host_version?,
         *           run, events, permissions, artifacts, latest_checkpoint }
         *
         *     Phase 5'+ used to return only `{run, events}`, so the
         *     `DiagnosticsPanel` rendered NaN counts (permissions.length on
         *     undefined) and the "latest checkpoint" tab was always missing.
         */
        get: operations["run_diagnostics_local_v1_runs__run_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_local_v1_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run */
        get: operations["stream_run_local_v1_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cloud Session */
        get: operations["get_cloud_session_local_v1_session_get"];
        put?: never;
        /**
         * Set Cloud Session
         * @description Stash a cloud bearer token (+ base URL) for outbound LLM calls.
         *
         *     Response shape MUST match the client's `LocalCloudSession` TypeScript
         *     interface — the client gates its "use local agent" feature flag on
         *     `session.connected === true`. The pydantic model + response_model
         *     now enforce that.
         */
        post: operations["set_cloud_session_local_v1_session_post"];
        /** Clear Cloud Session */
        delete: operations["clear_cloud_session_local_v1_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Local Skills */
        get: operations["list_local_skills_local_v1_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/skills/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install Skill */
        post: operations["install_skill_local_v1_skills_install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/skills/registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Skill Registry
         * @description Phase 5' stub: no external skill registry wired yet.
         */
        get: operations["search_skill_registry_local_v1_skills_registry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tools */
        get: operations["list_tools_local_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_local_v1_workspaces_get"];
        put?: never;
        /**
         * Add Workspace
         * @description Authorize a workspace path. Returns the flat row — the TS
         *     `authorizeLocalWorkspace` reads `.id / .path / .label` directly
         *     (no wrapper).
         */
        post: operations["add_workspace_local_v1_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/workspaces/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diagnose Workspace
         * @description Inspect a candidate path against the authorization registry.
         *
         *     Response matches the TS `LocalWorkspaceDiagnosis` shape — the
         *     `reason` enum drives the workspace-picker's "why disabled?"
         *     copy, keep it stable.
         */
        post: operations["diagnose_workspace_local_v1_workspaces_diagnose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/local/v1/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Workspace
         * @description Revoke a workspace authorization. Returns the deleted row
         *     matching the TS `revokeLocalWorkspace` →
         *     `Promise<LocalWorkspaceAuthorization>` signature.
         */
        delete: operations["remove_workspace_local_v1_workspaces__workspace_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerQuestionRequest */
        AnswerQuestionRequest: {
            /** Answers */
            answers: {
                [key: string]: string[];
            };
        };
        /** CancelRunResponse */
        CancelRunResponse: {
            /** Canceled */
            canceled: boolean;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Goal */
            goal: string;
            /** History */
            history?: {
                [key: string]: string;
            }[] | null;
            /**
             * Mode
             * @default fast
             */
            mode: string;
            /** Parent Run Id */
            parent_run_id?: string | null;
            /** Settings */
            settings?: {
                [key: string]: unknown;
            } | null;
            /** Workspace Path */
            workspace_path?: string | null;
        };
        /** CreateWorkspaceRequest */
        CreateWorkspaceRequest: {
            /**
             * Label
             * @default
             */
            label: string;
            /** Path */
            path: string;
        };
        /** DiagnoseWorkspaceRequest */
        DiagnoseWorkspaceRequest: {
            /** Path */
            path: string;
        };
        /** DiagnosticsArtifact */
        DiagnosticsArtifact: {
            /** Bytes */
            bytes: number;
            /** Content Type */
            content_type: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            /** Title */
            title: string;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Tool Name */
            tool_name?: string | null;
        };
        /**
         * DiagnosticsEvent
         * @description One row from the `local_events` table after payload parsing.
         *
         *     Matches the AgentRunEvent envelope the client's
         *     `parseAgentSSEChunk` produces (intentional, so the diagnostics
         *     panel can reuse the live-stream renderer).
         */
        DiagnosticsEvent: {
            /** Created At */
            created_at: string;
            /** Event Type */
            event_type: string;
            /** Id */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            /** Seq */
            seq: number;
        };
        /** DiagnosticsPermission */
        DiagnosticsPermission: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Resolved At */
            resolved_at?: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Scope
             * @default once
             * @enum {string}
             */
            scope: "once" | "run";
            /** Status */
            status: string;
            /** Tool Call Id */
            tool_call_id?: string | null;
            /** Tool Name */
            tool_name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description GET /local/v1/health — no auth required.
         *
         *     Both `ok` (legacy smoke contract) and `status` (current TS client
         *     probe) are returned. Drop `ok` once smoke scripts are updated.
         */
        HealthResponse: {
            /**
             * Mode
             * @default ready
             */
            mode: string;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Pairing Configured */
            pairing_configured: boolean;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /**
             * Worker
             * @default python-langgraph
             */
            worker: string;
        };
        /**
         * LatestCheckpoint
         * @description Slim summary of the agent run's last persisted superstep — used
         *     by the diagnostics panel to render the "where the run is paused"
         *     headline. The full LangGraph checkpoint is much larger; we just
         *     expose the fields the UI reads (`id`, `reason`, `messages_count`).
         */
        LatestCheckpoint: {
            /** Created At */
            created_at?: string | null;
            /** Id */
            id: string;
            /** Messages Count */
            messages_count: number;
            /** Reason */
            reason: string;
            /** Run Id */
            run_id?: string | null;
            /** Step */
            step: number;
        };
        /** ListRunsResponse */
        ListRunsResponse: {
            /** Runs */
            runs: components["schemas"]["LocalRun"][];
        };
        /** ListWorkspacesResponse */
        ListWorkspacesResponse: {
            /** Workspaces */
            workspaces: components["schemas"]["LocalWorkspaceAuthorization"][];
        };
        /**
         * LocalArtifact
         * @description Slim representation for `GET /artifacts/:id` (UI quoting).
         *
         *     The full row in `local_artifacts` (run_id, kind, content_type,
         *     bytes, metadata_json) is intentionally NOT returned here — that
         *     payload is for the diagnostics panel, not the chat surface.
         */
        LocalArtifact: {
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Tool Name */
            tool_name?: string | null;
        };
        /**
         * LocalCloudSession
         * @description Pairing state between the daemon and the cloud API.
         *
         *     `connected: false` is the only field on an unpaired response; the
         *     rest become present once the user logs in via the Electron app
         *     and the renderer POSTs the JWT to /local/v1/session.
         */
        LocalCloudSession: {
            /** Auth */
            auth?: "bearer" | null;
            /** Cloud Base Url */
            cloud_base_url?: string | null;
            /** Connected */
            connected: boolean;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * LocalRun
         * @description One row of the `local_runs` table, surfaced over HTTP.
         *
         *     `history_json` / `settings_json` are stringified JSON because
         *     SQLite stores them that way — the client parses on demand. Kept
         *     as strings here (not dict) to keep the wire format honest.
         */
        LocalRun: {
            /** Canceled At */
            canceled_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Created At */
            created_at: string;
            /** Events Count */
            events_count?: number | null;
            /** Goal */
            goal: string;
            /**
             * History Json
             * @default []
             */
            history_json: string;
            /** Id */
            id: string;
            /** Parent Run Id */
            parent_run_id?: string | null;
            /**
             * Settings Json
             * @default {}
             */
            settings_json: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "waiting_permission" | "waiting_input" | "completed" | "canceled" | "failed";
            /** Updated At */
            updated_at: string;
            /** Workspace Path */
            workspace_path?: string | null;
        };
        /** LocalRunDiagnostics */
        LocalRunDiagnostics: {
            /** Artifacts */
            artifacts: components["schemas"]["DiagnosticsArtifact"][];
            /** Events */
            events: components["schemas"]["DiagnosticsEvent"][];
            /** Exported At */
            exported_at: string;
            latest_checkpoint?: components["schemas"]["LatestCheckpoint"] | null;
            /** Local Host Version */
            local_host_version?: string | null;
            /** Permissions */
            permissions: components["schemas"]["DiagnosticsPermission"][];
            run: components["schemas"]["LocalRun"];
            /**
             * Schema Version
             * @default 1
             * @constant
             */
            schema_version: 1;
        };
        /** LocalWorkspaceAuthorization */
        LocalWorkspaceAuthorization: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Last Used At */
            last_used_at: string;
            /** Path */
            path: string;
        };
        /**
         * LocalWorkspaceDiagnosis
         * @description Result of POST /local/v1/workspaces/diagnose. The `reason` field
         *     drives the workspace-picker UI's "why is this disabled?" copy —
         *     keep the enum stable.
         */
        LocalWorkspaceDiagnosis: {
            /** Authorized */
            authorized: boolean;
            /** Exists */
            exists: boolean;
            /** Is Directory */
            is_directory: boolean;
            /** Path */
            path: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "authorized" | "not_authorized" | "not_found" | "not_directory";
            workspace?: components["schemas"]["LocalWorkspaceAuthorization"] | null;
        };
        /** PermissionResolution */
        PermissionResolution: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "deny";
            /** Permission Id */
            permission_id: string;
            /**
             * Resolved
             * @default true
             * @constant
             */
            resolved: true;
            /** Resumed */
            resumed: boolean;
            /**
             * Scope
             * @enum {string}
             */
            scope: "once" | "run";
        };
        /** QuestionAnswer */
        QuestionAnswer: {
            /**
             * Answered
             * @default true
             * @constant
             */
            answered: true;
            /** Question Id */
            question_id: string;
            /** Resumed */
            resumed: boolean;
        };
        /** ResolvePermissionRequest */
        ResolvePermissionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approve" | "deny";
            /**
             * Scope
             * @default once
             * @enum {string}
             */
            scope: "once" | "run";
        };
        /** ResumeRunResponse */
        ResumeRunResponse: {
            /**
             * Resumed
             * @default true
             * @constant
             */
            resumed: true;
        };
        /** SetCloudSessionRequest */
        SetCloudSessionRequest: {
            /** Access Token */
            access_token: string;
            /** Cloud Base Url */
            cloud_base_url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_artifact_local_v1_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalArtifact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_local_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    resolve_permission_local_v1_permissions__permission_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                permission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolvePermissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionResolution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_question_local_v1_questions__question_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionAnswer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_local_v1_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRunsResponse"];
                };
            };
        };
    };
    create_run_local_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_local_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_local_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_diagnostics_local_v1_runs__run_id__diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalRunDiagnostics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_local_v1_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_local_v1_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cloud_session_local_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalCloudSession"];
                };
            };
        };
    };
    set_cloud_session_local_v1_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCloudSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalCloudSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_cloud_session_local_v1_session_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalCloudSession"];
                };
            };
        };
    };
    list_local_skills_local_v1_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    install_skill_local_v1_skills_install_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_skill_registry_local_v1_skills_registry_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tools_local_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_workspaces_local_v1_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWorkspacesResponse"];
                };
            };
        };
    };
    add_workspace_local_v1_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalWorkspaceAuthorization"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnose_workspace_local_v1_workspaces_diagnose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnoseWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalWorkspaceDiagnosis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_workspace_local_v1_workspaces__workspace_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocalWorkspaceAuthorization"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
